# Generated by makeXDC.ulp developed by Sven Raiser, Tuebingen, Germany
#
# Board:     Q:/FFM-A7100-V3r0.brd
# Part Name: FPGA
# Part pkg:  BGA484
# Created:   02.04.2018 15:56:17

set_property CFGBVS VCCO [current_design]
#where value1 is either VCCO or GND

set_property CONFIG_VOLTAGE 3.3 [current_design]
#where value2 is the voltage provided to configuration bank 0

#
#	Clocks, resets & LEDs (no LEDs)
#
#set_property -dict {PACKAGE_PIN T4 IOSTANDARD LVTTL} [get_ports 100MHZ_N]
#set_property -dict {PACKAGE_PIN R4 IOSTANDARD LVTTL} [get_ports 100MHZ_P]
#set_property -dict {PACKAGE_PIN V13 IOSTANDARD LVTTL} [get_ports PON_RESET_N]
#set_property -dict {PACKAGE_PIN Y8 IOSTANDARD LVTTL} [get_ports PS_SRST_N]


#
#	SPI-Flash & external programming
#
#set_property -dict {PACKAGE_PIN H20 IOSTANDARD LVTTL} [get_ports SS0]
#set_property -dict {PACKAGE_PIN H18 IOSTANDARD LVTTL} [get_ports SS2_FPGA]
#set_property -dict {PACKAGE_PIN G20 IOSTANDARD LVTTL} [get_ports SS3_OSD]
#set_property -dict {PACKAGE_PIN G18 IOSTANDARD LVTTL} [get_ports SS4_SD_DIRECT]
#set_property -dict {PACKAGE_PIN L12 IOSTANDARD LVTTL} [get_ports FPGA_CCLK_INTERNAL]
set_property -dict {PACKAGE_PIN T19 IOSTANDARD LVTTL} [get_ports CSB_ext]
set_property -dict {PACKAGE_PIN P21 IOSTANDARD LVTTL} [get_ports IO2]
set_property -dict {PACKAGE_PIN R21 IOSTANDARD LVTTL} [get_ports IO3]
#set_property -dict {PACKAGE_PIN U10 IOSTANDARD LVTTL} [get_ports FPGA_M1]
#set_property -dict {PACKAGE_PIN U9 IOSTANDARD LVTTL} [get_ports FPGA_M2]
set_property -dict {PACKAGE_PIN R22 IOSTANDARD LVTTL} [get_ports MISO_ext]
set_property -dict {PACKAGE_PIN P22 IOSTANDARD LVTTL} [get_ports MOSI_ext]
#set_property -dict {PACKAGE_PIN G11 IOSTANDARD LVTTL} [get_ports FC_DONE]
#set_property -dict {PACKAGE_PIN U12 IOSTANDARD LVTTL} [get_ports FC_INIT_NCONFIG]
#set_property -dict {PACKAGE_PIN N12 IOSTANDARD LVTTL} [get_ports FC_PROG_NSTATUS]


#
#	FIOs (unassigned part)
#
set_property -dict {PACKAGE_PIN M17 IOSTANDARD LVTTL} [get_ports RLED]
set_property -dict {PACKAGE_PIN L16 IOSTANDARD LVTTL} [get_ports GLED]
#set_property -dict {PACKAGE_PIN L20 IOSTANDARD LVTTL} [get_ports FIO_2]
#set_property -dict {PACKAGE_PIN L19 IOSTANDARD LVTTL} [get_ports FIO_3]
#set_property -dict {PACKAGE_PIN K16 IOSTANDARD LVTTL} [get_ports FIO_4]
#set_property -dict {PACKAGE_PIN K17 IOSTANDARD LVTTL} [get_ports FIO_5]
#set_property -dict {PACKAGE_PIN J17 IOSTANDARD LVTTL} [get_ports FIO_6]
#set_property -dict {PACKAGE_PIN H17 IOSTANDARD LVTTL} [get_ports FIO_7]

#
#	Other
#

#set_property -dict {PACKAGE_PIN V12 IOSTANDARD LVTTL} [get_ports FPGA_TCK]
#set_property -dict {PACKAGE_PIN R13 IOSTANDARD LVTTL} [get_ports FPGA_TDI]
#set_property -dict {PACKAGE_PIN U13 IOSTANDARD LVTTL} [get_ports FPGA_TDO]
#set_property -dict {PACKAGE_PIN T13 IOSTANDARD LVTTL} [get_ports FPGA_TMS]

#set_property -dict {PACKAGE_PIN F8 IOSTANDARD LVTTL} [get_ports N$118]


# ORG
# NET "MISO_ext" LOC = A25; NET "MISO_ext" IOSTANDARD = LVCMOS33;
# NET "CSB_ext" LOC = C23; NET "CSB_ext" IOSTANDARD = LVCMOS33;
# NET "MOSI_ext" LOC = B24; NET "MOSI_ext" IOSTANDARD = LVCMOS33;
# NET "RLED" LOC = D26; NET "RLED" IOSTANDARD = LVCMOS33;
# NET "GLED" LOC = E26; NET "GLED" IOSTANDARD = LVCMOS33;
# NET "IO2" LOC = B22; NET "IO3" LOC = A22;
# NET "IO2" IOSTANDARD = LVCMOS33; NET "IO3" IOSTANDARD = LVCMOS33;







