
PROG = c2_sprites

CXXFILES = Compositing/Compositing.cpp c2_sprites.cpp

# default is 8bpp if unspecified
#CFLAGS += -DSOC_VIDEO_BPP=8

# for 16bpp color video bitstream use this
#CFLAGS += -DSOC_VIDEO_BPP=16

WITHOUT_FLOAT = true

include ${POST_MK}
