# Board:     ESA11-7A35i-V0.1.brd
# Part Name: FPGA XC7A35T-FGG484, Speedgrade: -2
# Part pkg:  BGA484
# Memory Device: DDR3_SDRAM->Components->MT41J128M16XX-125
# Created:   31.03.2015 10:47:48
# Edited:    2015-08-19, by emu

#
#	VGA
#

# set_property PACKAGE_PIN C17 [get_ports VGA_BLANK_N]
# set_property IOSTANDARD LVTTL [get_ports VGA_BLANK_N]
# set_property DRIVE 4 [get_ports VGA_BLANK_N]
# set_property PACKAGE_PIN C19 [get_ports VGA_BLUE[0]]
# set_property IOSTANDARD LVTTL [get_ports VGA_BLUE[0]]
# set_property DRIVE 4 [get_ports VGA_BLUE[0]]
# set_property PACKAGE_PIN A18 [get_ports VGA_BLUE[1]]
# set_property IOSTANDARD LVTTL [get_ports VGA_BLUE[1]]
# set_property DRIVE 4 [get_ports VGA_BLUE[1]]
# set_property PACKAGE_PIN D19 [get_ports VGA_BLUE[2]]
# set_property IOSTANDARD LVTTL [get_ports VGA_BLUE[2]]
# set_property DRIVE 4 [get_ports VGA_BLUE[2]]
# set_property PACKAGE_PIN A19 [get_ports VGA_BLUE[3]]
# set_property IOSTANDARD LVTTL [get_ports VGA_BLUE[3]]
# set_property DRIVE 4 [get_ports VGA_BLUE[3]]
# set_property PACKAGE_PIN C18 [get_ports VGA_BLUE[4]]
# set_property IOSTANDARD LVTTL [get_ports VGA_BLUE[4]]
# set_property DRIVE 4 [get_ports VGA_BLUE[4]]
# set_property PACKAGE_PIN B20 [get_ports VGA_BLUE[5]]
# set_property IOSTANDARD LVTTL [get_ports VGA_BLUE[5]]
# set_property DRIVE 4 [get_ports VGA_BLUE[5]]
# set_property PACKAGE_PIN E18 [get_ports VGA_BLUE[6]]
# set_property IOSTANDARD LVTTL [get_ports VGA_BLUE[6]]
# set_property DRIVE 4 [get_ports VGA_BLUE[6]]
# set_property PACKAGE_PIN A20 [get_ports VGA_BLUE[7]]
# set_property IOSTANDARD LVTTL [get_ports VGA_BLUE[7]]
# set_property DRIVE 4 [get_ports VGA_BLUE[7]]
# set_property PACKAGE_PIN D17 [get_ports VGA_CLOCK_P]
# set_property IOSTANDARD LVTTL [get_ports VGA_CLOCK_P]
# set_property DRIVE 4 [get_ports VGA_CLOCK_P]
# set_property PACKAGE_PIN A13 [get_ports VGA_GREEN[0]]
# set_property IOSTANDARD LVTTL [get_ports VGA_GREEN[0]]
# set_property DRIVE 4 [get_ports VGA_GREEN[0]]
# set_property PACKAGE_PIN B13 [get_ports VGA_GREEN[1]]
# set_property IOSTANDARD LVTTL [get_ports VGA_GREEN[1]]
# set_property DRIVE 4 [get_ports VGA_GREEN[1]]
# set_property PACKAGE_PIN A14 [get_ports VGA_GREEN[2]]
# set_property IOSTANDARD LVTTL [get_ports VGA_GREEN[2]]
# set_property DRIVE 4 [get_ports VGA_GREEN[2]]
# set_property PACKAGE_PIN B15 [get_ports VGA_GREEN[3]]
# set_property IOSTANDARD LVTTL [get_ports VGA_GREEN[3]]
# set_property DRIVE 4 [get_ports VGA_GREEN[3]]
# set_property PACKAGE_PIN A15 [get_ports VGA_GREEN[4]]
# set_property IOSTANDARD LVTTL [get_ports VGA_GREEN[4]]
# set_property DRIVE 4 [get_ports VGA_GREEN[4]]
# set_property PACKAGE_PIN B16 [get_ports VGA_GREEN[5]]
# set_property IOSTANDARD LVTTL [get_ports VGA_GREEN[5]]
# set_property DRIVE 4 [get_ports VGA_GREEN[5]]
# set_property PACKAGE_PIN A16 [get_ports VGA_GREEN[6]]
# set_property IOSTANDARD LVTTL [get_ports VGA_GREEN[6]]
# set_property DRIVE 4 [get_ports VGA_GREEN[6]]
# set_property PACKAGE_PIN B17 [get_ports VGA_GREEN[7]]
# set_property IOSTANDARD LVTTL [get_ports VGA_GREEN[7]]
# set_property DRIVE 4 [get_ports VGA_GREEN[7]]
# set_property PACKAGE_PIN E19 [get_ports VGA_HSYNC]
# set_property IOSTANDARD LVTTL [get_ports VGA_HSYNC]
# set_property DRIVE 4 [get_ports VGA_HSYNC]
# set_property PACKAGE_PIN D16 [get_ports VGA_RED[0]]
# set_property IOSTANDARD LVTTL [get_ports VGA_RED[0]]
# set_property DRIVE 4 [get_ports VGA_RED[0]]
# set_property PACKAGE_PIN E16 [get_ports VGA_RED[1]]
# set_property IOSTANDARD LVTTL [get_ports VGA_RED[1]]
# set_property DRIVE 4 [get_ports VGA_RED[1]]
# set_property PACKAGE_PIN C15 [get_ports VGA_RED[2]]
# set_property IOSTANDARD LVTTL [get_ports VGA_RED[2]]
# set_property DRIVE 4 [get_ports VGA_RED[2]]
# set_property PACKAGE_PIN D15 [get_ports VGA_RED[3]]
# set_property IOSTANDARD LVTTL [get_ports VGA_RED[3]]
# set_property DRIVE 4 [get_ports VGA_RED[3]]
# set_property PACKAGE_PIN F14 [get_ports VGA_RED[4]]
# set_property IOSTANDARD LVTTL [get_ports VGA_RED[4]]
# set_property DRIVE 4 [get_ports VGA_RED[4]]
# set_property PACKAGE_PIN C14 [get_ports VGA_RED[5]]
# set_property IOSTANDARD LVTTL [get_ports VGA_RED[5]]
# set_property DRIVE 4 [get_ports VGA_RED[5]]
# set_property PACKAGE_PIN D14 [get_ports VGA_RED[6]]
# set_property IOSTANDARD LVTTL [get_ports VGA_RED[6]]
# set_property DRIVE 4 [get_ports VGA_RED[6]]
# set_property PACKAGE_PIN E14 [get_ports VGA_RED[7]]
# set_property IOSTANDARD LVTTL [get_ports VGA_RED[7]]
# set_property DRIVE 4 [get_ports VGA_RED[7]]
# set_property PACKAGE_PIN B18 [get_ports VGA_SYNC_N]
# set_property IOSTANDARD LVTTL [get_ports VGA_SYNC_N]
# set_property DRIVE 4 [get_ports VGA_SYNC_N]
# set_property PACKAGE_PIN E17 [get_ports VGA_VSYNC]
# set_property IOSTANDARD LVTTL [get_ports VGA_VSYNC]
# set_property DRIVE 4 [get_ports VGA_VSYNC]

#
#	PS/2
#

# set_property PACKAGE_PIN G17 [get_ports VGA_PS2_A_CLK]
# set_property IOSTANDARD LVTTL [get_ports VGA_PS2_A_CLK]
# set_property DRIVE 4 [get_ports VGA_PS2_A_CLK]
# set_property PACKAGE_PIN G18 [get_ports VGA_PS2_A_DATA]
# set_property IOSTANDARD LVTTL [get_ports VGA_PS2_A_DATA]
# set_property DRIVE 4 [get_ports VGA_PS2_A_DATA]
# set_property PACKAGE_PIN H18 [get_ports VGA_PS2_B_CLK]
# set_property IOSTANDARD LVTTL [get_ports VGA_PS2_B_CLK]
# set_property DRIVE 4 [get_ports VGA_PS2_B_CLK]
# set_property PACKAGE_PIN H17 [get_ports VGA_PS2_B_DATA]
# set_property IOSTANDARD LVTTL [get_ports VGA_PS2_B_DATA]
# set_property DRIVE 4 [get_ports VGA_PS2_B_DATA]



#
#	EXPMODs
#


# set_property PACKAGE_PIN J22 [get_ports EXPMOD1[1]]
# set_property IOSTANDARD LVTTL [get_ports EXPMOD1[1]]
# set_property DRIVE 4 [get_ports EXPMOD1[1]]
# set_property PACKAGE_PIN H22 [get_ports EXPMOD1[2]]
# set_property IOSTANDARD LVTTL [get_ports EXPMOD1[2]]
# set_property DRIVE 4 [get_ports EXPMOD1[2]]
# set_property PACKAGE_PIN K22 [get_ports EXPMOD1[3]]
# set_property IOSTANDARD LVTTL [get_ports EXPMOD1[3]]
# set_property DRIVE 4 [get_ports EXPMOD1[3]]
# set_property PACKAGE_PIN H20 [get_ports EXPMOD1[4]]
# set_property IOSTANDARD LVTTL [get_ports EXPMOD1[4]]
# set_property DRIVE 4 [get_ports EXPMOD1[4]]
# set_property PACKAGE_PIN J19 [get_ports EXPMOD1[5]]
# set_property IOSTANDARD LVTTL [get_ports EXPMOD1[5]]
# set_property DRIVE 4 [get_ports EXPMOD1[5]]
# set_property PACKAGE_PIN J21 [get_ports EXPMOD1[6]]
# set_property IOSTANDARD LVTTL [get_ports EXPMOD1[6]]
# set_property DRIVE 4 [get_ports EXPMOD1[6]]
# set_property PACKAGE_PIN J20 [get_ports EXPMOD1[7]]
# set_property IOSTANDARD LVTTL [get_ports EXPMOD1[7]]
# set_property DRIVE 4 [get_ports EXPMOD1[7]]
# set_property PACKAGE_PIN K21 [get_ports EXPMOD1[8]]
# set_property IOSTANDARD LVTTL [get_ports EXPMOD1[8]]
# set_property DRIVE 4 [get_ports EXPMOD1[8]]
# set_property PACKAGE_PIN M16 [get_ports EXPMOD2[1]]
# set_property IOSTANDARD LVTTL [get_ports EXPMOD2[1]]
# set_property DRIVE 4 [get_ports EXPMOD2[1]]
# set_property PACKAGE_PIN M13 [get_ports EXPMOD2[2]]
# set_property IOSTANDARD LVTTL [get_ports EXPMOD2[2]]
# set_property DRIVE 4 [get_ports EXPMOD2[2]]
# set_property PACKAGE_PIN M15 [get_ports EXPMOD2[3]]
# set_property IOSTANDARD LVTTL [get_ports EXPMOD2[3]]
# set_property DRIVE 4 [get_ports EXPMOD2[3]]
# set_property PACKAGE_PIN L13 [get_ports EXPMOD2[4]]
# set_property IOSTANDARD LVTTL [get_ports EXPMOD2[4]]
# set_property DRIVE 4 [get_ports EXPMOD2[4]]
# set_property PACKAGE_PIN L15 [get_ports EXPMOD2[5]]
# set_property IOSTANDARD LVTTL [get_ports EXPMOD2[5]]
# set_property DRIVE 4 [get_ports EXPMOD2[5]]
# set_property PACKAGE_PIN K13 [get_ports EXPMOD2[6]]
# set_property IOSTANDARD LVTTL [get_ports EXPMOD2[6]]
# set_property DRIVE 4 [get_ports EXPMOD2[6]]
# set_property PACKAGE_PIN L14 [get_ports EXPMOD2[7]]
# set_property IOSTANDARD LVTTL [get_ports EXPMOD2[7]]
# set_property DRIVE 4 [get_ports EXPMOD2[7]]
# set_property PACKAGE_PIN K14 [get_ports EXPMOD2[8]]
# set_property IOSTANDARD LVTTL [get_ports EXPMOD2[8]]
# set_property DRIVE 4 [get_ports EXPMOD2[8]]

#
#	SATA1 & SATA2
#
# set_property PACKAGE_PIN V3 [get_ports SATA1_RX_N]
# set_property IOSTANDARD LVTTL [get_ports SATA1_RX_N]
# set_property DRIVE 4 [get_ports SATA1_RX_N]
# set_property PACKAGE_PIN U3 [get_ports SATA1_RX_P]
# set_property IOSTANDARD LVTTL [get_ports SATA1_RX_P]
# set_property DRIVE 4 [get_ports SATA1_RX_P]
# set_property PACKAGE_PIN V2 [get_ports SATA1_TX_N]
# set_property IOSTANDARD LVTTL [get_ports SATA1_TX_N]
# set_property DRIVE 4 [get_ports SATA1_TX_N]
# set_property PACKAGE_PIN U2 [get_ports SATA1_TX_P]
# set_property IOSTANDARD LVTTL [get_ports SATA1_TX_P]
# set_property DRIVE 4 [get_ports SATA1_TX_P]
# set_property PACKAGE_PIN U1 [get_ports SATA2_RX_N]
# set_property IOSTANDARD LVTTL [get_ports SATA2_RX_N]
# set_property DRIVE 4 [get_ports SATA2_RX_N]
# set_property PACKAGE_PIN T1 [get_ports SATA2_RX_P]
# set_property IOSTANDARD LVTTL [get_ports SATA2_RX_P]
# set_property DRIVE 4 [get_ports SATA2_RX_P]
# set_property PACKAGE_PIN Y1 [get_ports SATA2_TX_N]
# set_property IOSTANDARD LVTTL [get_ports SATA2_TX_N]
# set_property DRIVE 4 [get_ports SATA2_TX_N]
# set_property PACKAGE_PIN W1 [get_ports SATA2_TX_P]
# set_property IOSTANDARD LVTTL [get_ports SATA2_TX_P]
# set_property DRIVE 4 [get_ports SATA2_TX_P]

#
#	Programming, Config & Communication with ATMEL MCU
#
# set_property PACKAGE_PIN J17 [get_ports SS2/FPGA]
# set_property IOSTANDARD LVTTL [get_ports SS2/FPGA]
# set_property DRIVE 4 [get_ports SS2/FPGA]
# set_property PACKAGE_PIN F18 [get_ports SS3/OSD]
# set_property IOSTANDARD LVTTL [get_ports SS3/OSD]
# set_property DRIVE 4 [get_ports SS3/OSD]
# set_property PACKAGE_PIN F19 [get_ports SS4/SD_DIRECT]
# set_property IOSTANDARD LVTTL [get_ports SS4/SD_DIRECT]
# set_property DRIVE 4 [get_ports SS4/SD_DIRECT]
# set_property PACKAGE_PIN G20 [get_ports MCU_SD_CMD/MOSI]
# set_property IOSTANDARD LVTTL [get_ports MCU_SD_CMD/MOSI]
# set_property DRIVE 4 [get_ports MCU_SD_CMD/MOSI]
# set_property PACKAGE_PIN H19 [get_ports MCU_SD_SCLK//SCK]
# set_property IOSTANDARD LVTTL [get_ports MCU_SD_SCLK//SCK]
# set_property DRIVE 4 [get_ports MCU_SD_SCLK//SCK]
# set_property PACKAGE_PIN F21 [get_ports OTC_OC]
# set_property IOSTANDARD LVTTL [get_ports OTC_OC]
# set_property DRIVE 4 [get_ports OTC_OC]

# set_property PACKAGE_PIN R22 [get_ports FPGA_MISO_INTERNAL]
# set_property IOSTANDARD LVTTL [get_ports FPGA_MISO_INTERNAL]
# set_property DRIVE 4 [get_ports FPGA_MISO_INTERNAL]
# set_property PACKAGE_PIN P22 [get_ports FPGA_MOSI]
# set_property IOSTANDARD LVTTL [get_ports FPGA_MOSI]
# set_property DRIVE 4 [get_ports FPGA_MOSI]
# set_property PACKAGE_PIN N12 [get_ports FPGA_PROG/CONF_NSTATUS]
# set_property IOSTANDARD LVTTL [get_ports FPGA_PROG/CONF_NSTATUS]
# set_property DRIVE 4 [get_ports FPGA_PROG/CONF_NSTATUS]


# set_property PACKAGE_PIN L12 [get_ports FPGA_CCLK_INTERNAL]
# set_property IOSTANDARD LVTTL [get_ports FPGA_CCLK_INTERNAL]
# set_property DRIVE 4 [get_ports FPGA_CCLK_INTERNAL]
# set_property PACKAGE_PIN T19 [get_ports FPGA_CSO]
# set_property IOSTANDARD LVTTL [get_ports FPGA_CSO]
# set_property DRIVE 4 [get_ports FPGA_CSO]
# set_property PACKAGE_PIN G11 [get_ports FPGA_DONE/CONF_DONE]
# set_property IOSTANDARD LVTTL [get_ports FPGA_DONE/CONF_DONE]
# set_property DRIVE 4 [get_ports FPGA_DONE/CONF_DONE]
# set_property PACKAGE_PIN U12 [get_ports FPGA_INIT/CONF_NCONFIG]
# set_property IOSTANDARD LVTTL [get_ports FPGA_INIT/CONF_NCONFIG]
# set_property DRIVE 4 [get_ports FPGA_INIT/CONF_NCONFIG]
# set_property PACKAGE_PIN U11 [get_ports FPGA_M0]
# set_property IOSTANDARD LVTTL [get_ports FPGA_M0]
# set_property DRIVE 4 [get_ports FPGA_M0]


#
#	USB3320 from microchip
#
# set_property PACKAGE_PIN B21 [get_ports USB_CLK]
# set_property IOSTANDARD LVTTL [get_ports USB_CLK]
# set_property DRIVE 4 [get_ports USB_CLK]
# set_property PACKAGE_PIN C22 [get_ports USB_D[0]]
# set_property IOSTANDARD LVTTL [get_ports USB_D[0]]
# set_property DRIVE 4 [get_ports USB_D[0]]
# set_property PACKAGE_PIN D20 [get_ports USB_D[1]]
# set_property IOSTANDARD LVTTL [get_ports USB_D[1]]
# set_property DRIVE 4 [get_ports USB_D[1]]
# set_property PACKAGE_PIN D22 [get_ports USB_D[2]]
# set_property IOSTANDARD LVTTL [get_ports USB_D[2]]
# set_property DRIVE 4 [get_ports USB_D[2]]
# set_property PACKAGE_PIN D21 [get_ports USB_D[3]]
# set_property IOSTANDARD LVTTL [get_ports USB_D[3]]
# set_property DRIVE 4 [get_ports USB_D[3]]
# set_property PACKAGE_PIN E22 [get_ports USB_D[4]]
# set_property IOSTANDARD LVTTL [get_ports USB_D[4]]
# set_property DRIVE 4 [get_ports USB_D[4]]
# set_property PACKAGE_PIN E21 [get_ports USB_D[5]]
# set_property IOSTANDARD LVTTL [get_ports USB_D[5]]
# set_property DRIVE 4 [get_ports USB_D[5]]
# set_property PACKAGE_PIN G22 [get_ports USB_D[6]]
# set_property IOSTANDARD LVTTL [get_ports USB_D[6]]
# set_property DRIVE 4 [get_ports USB_D[6]]
# set_property PACKAGE_PIN G21 [get_ports USB_D[7]]
# set_property IOSTANDARD LVTTL [get_ports USB_D[7]]
# set_property DRIVE 4 [get_ports USB_D[7]]
# set_property PACKAGE_PIN A21 [get_ports USB_DIR]
# set_property IOSTANDARD LVTTL [get_ports USB_DIR]
# set_property DRIVE 4 [get_ports USB_DIR]
# set_property PACKAGE_PIN B22 [get_ports USB_NXT]
# set_property IOSTANDARD LVTTL [get_ports USB_NXT]
# set_property DRIVE 4 [get_ports USB_NXT]
# set_property PACKAGE_PIN F20 [get_ports USB_RESET]
# set_property IOSTANDARD LVTTL [get_ports USB_RESET]
# set_property DRIVE 4 [get_ports USB_RESET]
# set_property PACKAGE_PIN C20 [get_ports USB_STP]
# set_property IOSTANDARD LVTTL [get_ports USB_STP]
# set_property DRIVE 4 [get_ports USB_STP]

#
#	Serial Video
#

# set_property PACKAGE_PIN N19 [get_ports VID_CLK_N]
# set_property IOSTANDARD LVTTL [get_ports VID_CLK_N]
# set_property DRIVE 4 [get_ports VID_CLK_N]
# set_property PACKAGE_PIN N18 [get_ports VID_CLK_P]
# set_property IOSTANDARD LVTTL [get_ports VID_CLK_P]
# set_property DRIVE 4 [get_ports VID_CLK_P]
# set_property PACKAGE_PIN M20 [get_ports VID_D0_N]
# set_property IOSTANDARD LVTTL [get_ports VID_D0_N]
# set_property DRIVE 4 [get_ports VID_D0_N]
# set_property PACKAGE_PIN N20 [get_ports VID_D0_P]
# set_property IOSTANDARD LVTTL [get_ports VID_D0_P]
# set_property DRIVE 4 [get_ports VID_D0_P]
# set_property PACKAGE_PIN L20 [get_ports VID_D1_N]
# set_property IOSTANDARD LVTTL [get_ports VID_D1_N]
# set_property DRIVE 4 [get_ports VID_D1_N]
# set_property PACKAGE_PIN L19 [get_ports VID_D1_P]
# set_property IOSTANDARD LVTTL [get_ports VID_D1_P]
# set_property DRIVE 4 [get_ports VID_D1_P]
# set_property PACKAGE_PIN K19 [get_ports VID_D2_N]
# set_property IOSTANDARD LVTTL [get_ports VID_D2_N]
# set_property DRIVE 4 [get_ports VID_D2_N]
# set_property PACKAGE_PIN K18 [get_ports VID_D2_P]
# set_property IOSTANDARD LVTTL [get_ports VID_D2_P]
# set_property DRIVE 4 [get_ports VID_D2_P]
# set_property PACKAGE_PIN M22 [get_ports VID_RSCL]
# set_property IOSTANDARD LVTTL [get_ports VID_RSCL]
# set_property DRIVE 4 [get_ports VID_RSCL]
# set_property PACKAGE_PIN N22 [get_ports VID_RSDA]
# set_property IOSTANDARD LVTTL [get_ports VID_RSDA]
# set_property DRIVE 4 [get_ports VID_RSDA]

#eof
