#vivado=/opt/Xilinx/Vivado/2015.3/bin/vivado
project=esa11_7a35i_bram
xc3sprog_interface = ft4232h
# name of resulting bitstream file (*.bit)
bitfile=$(project).runs/impl_1/glue.bit

include ../include/vivado.mk
