
PROG = vector_fractal

LIBS = -lm

CFILES    = Vector/vector_link.c

CXXFILES  = Vector/Vector.cpp 
CXXFILES += Compositing/Compositing.cpp
CXXFILES += vector_fractal.cpp

# default is 8bpp if unspecified
#CFLAGS += -DSOC_VIDEO_BPP=8

# for 16bpp color video bitstream use this
#CFLAGS += -DSOC_VIDEO_BPP=16

include ${POST_MK}
