
PROG = demo

CFILES = demo.c \
	../lib/sio.c ../lib/spi.c ../lib/div.c ../lib/atoi.c \
	../lib/printf.c ../lib/pcmplay.c ../lib/gets.c ../lib/random.c \
	../lib/sdcard.c ../lib/fatfs.c ../lib/diskio.c ../lib/sio_baud.c

ASFILES = ../lib/start.S

include ../conf/f32c.mk

