# Generated by makeXDC.ulp developed by Sven Raiser, Tuebingen, Germany
#
# Board:     ESA11-7A100t-V0.1.brd & EMS11-USER01
# Part Name: FPGA
# Part pkg:  BGA484
# Created:   07.07.2015 00:27:03


#
#	leds on module
#
set_property PACKAGE_PIN N18 [get_ports led[0]]
set_property IOSTANDARD LVTTL [get_ports led[0]]
set_property DRIVE 4 [get_ports led[0]]
set_property PACKAGE_PIN K18 [get_ports led[1]]
set_property IOSTANDARD LVTTL [get_ports led[1]]
set_property DRIVE 4 [get_ports led[1]]
set_property PACKAGE_PIN D21 [get_ports led[2]]
set_property IOSTANDARD LVTTL [get_ports led[2]]
set_property DRIVE 4 [get_ports led[2]]
set_property PACKAGE_PIN C22 [get_ports led[3]]
set_property IOSTANDARD LVTTL [get_ports led[3]]
set_property DRIVE 4 [get_ports led[3]]

set_property PACKAGE_PIN G16 [get_ports led[4]]
set_property IOSTANDARD LVTTL [get_ports led[4]]
set_property DRIVE 4 [get_ports led[4]]
set_property PACKAGE_PIN D17 [get_ports led[5]]
set_property IOSTANDARD LVTTL [get_ports led[5]]
set_property DRIVE 4 [get_ports led[5]]
set_property PACKAGE_PIN A14 [get_ports led[6]]
set_property IOSTANDARD LVTTL [get_ports led[6]]
set_property DRIVE 4 [get_ports led[6]]
set_property PACKAGE_PIN B15 [get_ports led[7]]
set_property IOSTANDARD LVTTL [get_ports led[7]]
set_property DRIVE 4 [get_ports led[7]]

#
#   EXPMOD_0
#
set_property PACKAGE_PIN J17 [get_ports EXPMOD1[1]]
set_property IOSTANDARD LVTTL [get_ports EXPMOD1[1]]
set_property DRIVE 4 [get_ports EXPMOD1[1]]
set_property PACKAGE_PIN K17 [get_ports EXPMOD1[0]]
set_property IOSTANDARD LVTTL [get_ports EXPMOD1[0]]
set_property DRIVE 4 [get_ports EXPMOD1[0]]
set_property PACKAGE_PIN L16 [get_ports EXPMOD1[3]]
set_property IOSTANDARD LVTTL [get_ports EXPMOD1[3]]
set_property DRIVE 4 [get_ports EXPMOD1[3]]
set_property PACKAGE_PIN M16 [get_ports EXPMOD1[2]]
set_property IOSTANDARD LVTTL [get_ports EXPMOD1[2]]
set_property DRIVE 4 [get_ports EXPMOD1[2]]
set_property PACKAGE_PIN M22 [get_ports EXPMOD1[5]]
set_property IOSTANDARD LVTTL [get_ports EXPMOD1[5]]
set_property DRIVE 4 [get_ports EXPMOD1[5]]
set_property PACKAGE_PIN M21 [get_ports EXPMOD1[4]]
set_property IOSTANDARD LVTTL [get_ports EXPMOD1[4]]
set_property DRIVE 4 [get_ports EXPMOD1[4]]
set_property PACKAGE_PIN N22 [get_ports EXPMOD1[7]]
set_property IOSTANDARD LVTTL [get_ports EXPMOD1[7]]
set_property DRIVE 4 [get_ports EXPMOD1[7]]
set_property PACKAGE_PIN N20 [get_ports EXPMOD1[6]]
set_property IOSTANDARD LVTTL [get_ports EXPMOD1[6]]
set_property DRIVE 4 [get_ports EXPMOD1[6]]

#
#   EXPMOD_1
#
set_property PACKAGE_PIN E21 [get_ports EXPMOD2[7]]
set_property IOSTANDARD LVTTL [get_ports EXPMOD2[7]]
set_property DRIVE 4 [get_ports EXPMOD2[7]]
set_property PACKAGE_PIN F21 [get_ports EXPMOD2[1]]
set_property IOSTANDARD LVTTL [get_ports EXPMOD2[1]]
set_property DRIVE 4 [get_ports EXPMOD2[1]]
set_property PACKAGE_PIN G22 [get_ports EXPMOD2[3]]
set_property IOSTANDARD LVTTL [get_ports EXPMOD2[3]]
set_property DRIVE 4 [get_ports EXPMOD2[3]]
set_property PACKAGE_PIN D22 [get_ports EXPMOD2[5]]
set_property IOSTANDARD LVTTL [get_ports EXPMOD2[5]]
set_property DRIVE 4 [get_ports EXPMOD2[5]]
set_property PACKAGE_PIN E22 [get_ports EXPMOD2[0]]
set_property IOSTANDARD LVTTL [get_ports EXPMOD2[0]]
set_property DRIVE 4 [get_ports EXPMOD2[0]]
set_property PACKAGE_PIN G21 [get_ports EXPMOD2[2]]
set_property IOSTANDARD LVTTL [get_ports EXPMOD2[2]]
set_property DRIVE 4 [get_ports EXPMOD2[2]]
set_property PACKAGE_PIN K16 [get_ports EXPMOD2[4]]
set_property IOSTANDARD LVTTL [get_ports EXPMOD2[4]]
set_property DRIVE 4 [get_ports EXPMOD2[4]]
set_property PACKAGE_PIN J16 [get_ports EXPMOD2[6]]
set_property IOSTANDARD LVTTL [get_ports EXPMOD2[6]]
set_property DRIVE 4 [get_ports EXPMOD2[6]]

#
#   EXPMOD_2
#
set_property PACKAGE_PIN F19 [get_ports EXPMOD3[2]]
set_property IOSTANDARD LVTTL [get_ports EXPMOD3[2]]
set_property DRIVE 4 [get_ports EXPMOD3[2]]
set_property PACKAGE_PIN G17 [get_ports EXPMOD3[0]]
set_property IOSTANDARD LVTTL [get_ports EXPMOD3[0]]
set_property DRIVE 4 [get_ports EXPMOD3[0]]
set_property PACKAGE_PIN G18 [get_ports EXPMOD3[6]]
set_property IOSTANDARD LVTTL [get_ports EXPMOD3[6]]
set_property DRIVE 4 [get_ports EXPMOD3[6]]
set_property PACKAGE_PIN G20 [get_ports EXPMOD3[1]]
set_property IOSTANDARD LVTTL [get_ports EXPMOD3[1]]
set_property DRIVE 4 [get_ports EXPMOD3[1]]
set_property PACKAGE_PIN H15 [get_ports EXPMOD3[4]]
set_property IOSTANDARD LVTTL [get_ports EXPMOD3[4]]
set_property DRIVE 4 [get_ports EXPMOD3[4]]
set_property PACKAGE_PIN F13 [get_ports EXPMOD3[7]]
set_property IOSTANDARD LVTTL [get_ports EXPMOD3[7]]
set_property DRIVE 4 [get_ports EXPMOD3[7]]
set_property PACKAGE_PIN F14 [get_ports EXPMOD3[5]]
set_property IOSTANDARD LVTTL [get_ports EXPMOD3[5]]
set_property DRIVE 4 [get_ports EXPMOD3[5]]
set_property PACKAGE_PIN F15 [get_ports EXPMOD3[3]]
set_property IOSTANDARD LVTTL [get_ports EXPMOD3[3]]
set_property DRIVE 4 [get_ports EXPMOD3[3]]

#
#   EXPMOD_3
#
set_property PACKAGE_PIN G15 [get_ports EXPMOD4[7]]
set_property IOSTANDARD LVTTL [get_ports EXPMOD4[7]]
set_property DRIVE 4 [get_ports EXPMOD4[7]]
set_property PACKAGE_PIN D16 [get_ports EXPMOD4[6]]
set_property IOSTANDARD LVTTL [get_ports EXPMOD4[6]]
set_property DRIVE 4 [get_ports EXPMOD4[6]]
set_property PACKAGE_PIN B17 [get_ports EXPMOD4[5]]
set_property IOSTANDARD LVTTL [get_ports EXPMOD4[5]]
set_property DRIVE 4 [get_ports EXPMOD4[5]]
set_property PACKAGE_PIN E16 [get_ports EXPMOD4[4]]
set_property IOSTANDARD LVTTL [get_ports EXPMOD4[4]]
set_property DRIVE 4 [get_ports EXPMOD4[4]]
set_property PACKAGE_PIN C17 [get_ports EXPMOD4[3]]
set_property IOSTANDARD LVTTL [get_ports EXPMOD4[3]]
set_property DRIVE 4 [get_ports EXPMOD4[3]]
set_property PACKAGE_PIN C18 [get_ports EXPMOD4[2]]
set_property IOSTANDARD LVTTL [get_ports EXPMOD4[2]]
set_property DRIVE 4 [get_ports EXPMOD4[2]]
set_property PACKAGE_PIN E17 [get_ports EXPMOD4[1]]
set_property IOSTANDARD LVTTL [get_ports EXPMOD4[1]]
set_property DRIVE 4 [get_ports EXPMOD4[1]]
set_property PACKAGE_PIN A13 [get_ports EXPMOD4[0]]
set_property IOSTANDARD LVTTL [get_ports EXPMOD4[0]]
set_property DRIVE 4 [get_ports EXPMOD4[0]]

#
#   Buttons
#
set_property PACKAGE_PIN H20 [get_ports t1]
set_property IOSTANDARD LVTTL [get_ports t1]
set_property DRIVE 4 [get_ports t1]
set_property PACKAGE_PIN H22 [get_ports t2]
set_property IOSTANDARD LVTTL [get_ports t2]
set_property DRIVE 4 [get_ports t2]
set_property PACKAGE_PIN J14 [get_ports t3]
set_property IOSTANDARD LVTTL [get_ports t3]
set_property DRIVE 4 [get_ports t3]
set_property PACKAGE_PIN J15 [get_ports t4]
set_property IOSTANDARD LVTTL [get_ports t4]
set_property DRIVE 4 [get_ports t4]

#
#   HEX-Switch
#
set_property PACKAGE_PIN D19 [get_ports hex[3]]
set_property IOSTANDARD LVTTL [get_ports hex[3]]
set_property DRIVE 4 [get_ports hex[3]]
set_property PACKAGE_PIN F20 [get_ports hex[2]]
set_property IOSTANDARD LVTTL [get_ports hex[2]]
set_property DRIVE 4 [get_ports hex[2]]
set_property PACKAGE_PIN E19 [get_ports hex[1]]
set_property IOSTANDARD LVTTL [get_ports hex[1]]
set_property DRIVE 4 [get_ports hex[1]]
set_property PACKAGE_PIN F18 [get_ports hex[0]]
set_property IOSTANDARD LVTTL [get_ports hex[0]]
set_property DRIVE 4 [get_ports hex[0]]

#
#   7-segment display
#
set_property PACKAGE_PIN M17 [get_ports seg[0]]
set_property IOSTANDARD LVTTL [get_ports seg[0]]
set_property DRIVE 4 [get_ports seg[0]]
set_property PACKAGE_PIN L18 [get_ports seg[1]]
set_property IOSTANDARD LVTTL [get_ports seg[1]]
set_property DRIVE 4 [get_ports seg[1]]
set_property PACKAGE_PIN L19 [get_ports seg[2]]
set_property IOSTANDARD LVTTL [get_ports seg[2]]
set_property DRIVE 4 [get_ports seg[2]]
set_property PACKAGE_PIN M18 [get_ports seg[3]]
set_property IOSTANDARD LVTTL [get_ports seg[3]]
set_property DRIVE 4 [get_ports seg[3]]
set_property PACKAGE_PIN K21 [get_ports seg[4]]
set_property IOSTANDARD LVTTL [get_ports seg[4]]
set_property DRIVE 4 [get_ports seg[4]]
set_property PACKAGE_PIN N19 [get_ports seg[5]]
set_property IOSTANDARD LVTTL [get_ports seg[5]]
set_property DRIVE 4 [get_ports seg[5]]
set_property PACKAGE_PIN M20 [get_ports seg[6]]
set_property IOSTANDARD LVTTL [get_ports seg[6]]
set_property DRIVE 4 [get_ports seg[6]]
set_property PACKAGE_PIN L20 [get_ports seg[7]]
set_property IOSTANDARD LVTTL [get_ports seg[7]]
set_property DRIVE 4 [get_ports seg[7]]

set_property PACKAGE_PIN J21 [get_ports an[0]]
set_property IOSTANDARD LVTTL [get_ports an[0]]
set_property DRIVE 4 [get_ports an[0]]
set_property PACKAGE_PIN H17 [get_ports an[1]]
set_property IOSTANDARD LVTTL [get_ports an[1]]
set_property DRIVE 4 [get_ports an[1]]
set_property PACKAGE_PIN J22 [get_ports an[2]]
set_property IOSTANDARD LVTTL [get_ports an[2]]
set_property DRIVE 4 [get_ports an[2]]
set_property PACKAGE_PIN K22 [get_ports an[3]]
set_property IOSTANDARD LVTTL [get_ports an[3]]
set_property DRIVE 4 [get_ports an[3]]


#
#   This is all wrong, just assigning used signals to I/O pins outside
#   we have onlhy 1 hex switch, other sw pins are 

# set_property PACKAGE_PIN AA6 [get_ports hex[4]]
# set_property IOSTANDARD LVTTL [get_ports hex[4]]
# set_property DRIVE 4 [get_ports hex[4]]
# set_property PACKAGE_PIN T4 [get_ports hex[5]]
# set_property IOSTANDARD LVTTL [get_ports hex[5]]
# set_property DRIVE 4 [get_ports hex[5]]
# set_property PACKAGE_PIN AB8 [get_ports hex[6]]
# set_property IOSTANDARD LVTTL [get_ports hex[6]]
# set_property DRIVE 4 [get_ports hex[6]]
# set_property PACKAGE_PIN AB7 [get_ports hex[7]]
# set_property IOSTANDARD LVTTL [get_ports hex[7]]
# set_property DRIVE 4 [get_ports hex[7]]












# set_property PACKAGE_PIN R21 [get_ports M_7SEG3_A]
# set_property IOSTANDARD LVTTL [get_ports M_7SEG3_A]
# set_property DRIVE 4 [get_ports M_7SEG3_A]
# set_property PACKAGE_PIN T20 [get_ports M_7SEG3_B]
# set_property IOSTANDARD LVTTL [get_ports M_7SEG3_B]
# set_property DRIVE 4 [get_ports M_7SEG3_B]
# set_property PACKAGE_PIN U21 [get_ports M_7SEG3_C]
# set_property IOSTANDARD LVTTL [get_ports M_7SEG3_C]
# set_property DRIVE 4 [get_ports M_7SEG3_C]
# set_property PACKAGE_PIN R18 [get_ports M_7SEG3_DP]
# set_property IOSTANDARD LVTTL [get_ports M_7SEG3_DP]
# set_property DRIVE 4 [get_ports M_7SEG3_DP]
# set_property PACKAGE_PIN W22 [get_ports M_7SEG2_C]
# set_property IOSTANDARD LVTTL [get_ports M_7SEG2_C]
# set_property DRIVE 4 [get_ports M_7SEG2_C]
# set_property PACKAGE_PIN V19 [get_ports M_7SEG2_B]
# set_property IOSTANDARD LVTTL [get_ports M_7SEG2_B]
# set_property DRIVE 4 [get_ports M_7SEG2_B]
# set_property PACKAGE_PIN Y21 [get_ports M_7SEG2_F]
# set_property IOSTANDARD LVTTL [get_ports M_7SEG2_F]
# set_property DRIVE 4 [get_ports M_7SEG2_F]
# set_property PACKAGE_PIN W19 [get_ports M_7SEG2_E]
# set_property IOSTANDARD LVTTL [get_ports M_7SEG2_E]
# set_property DRIVE 4 [get_ports M_7SEG2_E]






# set_property PACKAGE_PIN T21 [get_ports M_7SEG3_F]
# set_property IOSTANDARD LVTTL [get_ports M_7SEG3_F]
# set_property DRIVE 4 [get_ports M_7SEG3_F]
# set_property PACKAGE_PIN U22 [get_ports M_7SEG3_G]
# set_property IOSTANDARD LVTTL [get_ports M_7SEG3_G]
# set_property DRIVE 4 [get_ports M_7SEG3_G]
# set_property PACKAGE_PIN V22 [get_ports M_7SEG3_E]
# set_property IOSTANDARD LVTTL [get_ports M_7SEG3_E]
# set_property DRIVE 4 [get_ports M_7SEG3_E]
# set_property PACKAGE_PIN V20 [get_ports M_7SEG3_D]
# set_property IOSTANDARD LVTTL [get_ports M_7SEG3_D]
# set_property DRIVE 4 [get_ports M_7SEG3_D]
# set_property PACKAGE_PIN W21 [get_ports M_7SEG2_DP]
# set_property IOSTANDARD LVTTL [get_ports M_7SEG2_DP]
# set_property DRIVE 4 [get_ports M_7SEG2_DP]
# set_property PACKAGE_PIN Y22 [get_ports M_7SEG2_A]
# set_property IOSTANDARD LVTTL [get_ports M_7SEG2_A]
# set_property DRIVE 4 [get_ports M_7SEG2_A]
# set_property PACKAGE_PIN AB22 [get_ports M_7SEG2_G]
# set_property IOSTANDARD LVTTL [get_ports M_7SEG2_G]
# set_property DRIVE 4 [get_ports M_7SEG2_G]
# set_property PACKAGE_PIN AB21 [get_ports M_7SEG2_D]
# set_property IOSTANDARD LVTTL [get_ports M_7SEG2_D]
# set_property DRIVE 4 [get_ports M_7SEG2_D]

#
#   Spares
#
# set_property PACKAGE_PIN P19 [get_ports VG_C2]
# set_property IOSTANDARD LVTTL [get_ports VG_C2]
# set_property DRIVE 4 [get_ports VG_C2]
# set_property PACKAGE_PIN U7 [get_ports VG_C21]
# set_property IOSTANDARD LVTTL [get_ports VG_C21]
# set_property DRIVE 4 [get_ports VG_C21]