vivado=/opt/Xilinx/Vivado/2015.2/bin/vivado
project=zybo_cache_test
xc3sprog_interface = jtaghs1_fast
xc3sprog_device = 1
# name of resulting bitstream file (*.bit)
bitfile=$(project).runs/impl_1/glue.bit

include ../include/vivado.mk
