#vivado=/opt/Xilinx/Vivado/2015.3/bin/vivado
project=esa11_7a102t_xram_axiram_ddr3
xc3sprog_interface = ft4232h_fast
#xc3sprog_interface = ft4232h
# name of resulting bitstream file (*.bit)
bitfile=$(project).runs/impl_1/esa11_xram_axiram_ddr3.bit

junk=*~
junk+=.Xil vivado.log vivado.jou ip_upgrade.log
junk+=$(project).ip_user_files
junk+=$(project).sim
junk+=$(project).cache


junk+=$(project).srcs/sources_1/ip/clk_d100_100_200_250_25MHz/*.upgrade_log
junk+=$(project).srcs/sources_1/ip/clk_d100_100_200_250_25MHz/*.v
junk+=$(project).srcs/sources_1/ip/clk_d100_100_200_250_25MHz/*.vhdl
junk+=$(project).srcs/sources_1/ip/clk_d100_100_200_250_25MHz/*.dcp
junk+=$(project).srcs/sources_1/ip/clk_d100_100_200_250_25MHz/*.xml
junk+=$(project).srcs/sources_1/ip/clk_d100_100_200_250_25MHz/*.xdc
junk+=$(project).srcs/sources_1/ip/clk_d100_100_200_250_25MHz/*.veo
junk+=$(project).srcs/sources_1/ip/clk_d100_100_200_250_25MHz/*.vho
junk+=$(project).srcs/sources_1/ip/clk_d100_100_200_250_25MHz/*.tcl
junk+=$(project).srcs/sources_1/ip/clk_d100_100_200_250_25MHz/*.ncf
junk+=$(project).srcs/sources_1/ip/clk_d100_100_200_250_25MHz/*.log
junk+=$(project).srcs/sources_1/ip/clk_d100_100_200_250_25MHz/doc
junk+=$(project).srcs/sources_1/ip/clk_d100_100_200_250_25MHz/sim
junk+=$(project).srcs/sources_1/ip/clk_d100_100_200_250_25MHz/synth
junk+=$(project).srcs/sources_1/ip/clk_d100_100_200_250_25MHz/clk_wiz_v5_3_1

junk+=$(project).srcs/sources_1/ip/clk_d100_100_200_125_25MHz/*.upgrade_log
junk+=$(project).srcs/sources_1/ip/clk_d100_100_200_125_25MHz/*.v
junk+=$(project).srcs/sources_1/ip/clk_d100_100_200_125_25MHz/*.vhdl
junk+=$(project).srcs/sources_1/ip/clk_d100_100_200_125_25MHz/*.dcp
junk+=$(project).srcs/sources_1/ip/clk_d100_100_200_125_25MHz/*.xml
junk+=$(project).srcs/sources_1/ip/clk_d100_100_200_125_25MHz/*.xdc
junk+=$(project).srcs/sources_1/ip/clk_d100_100_200_125_25MHz/*.veo
junk+=$(project).srcs/sources_1/ip/clk_d100_100_200_125_25MHz/*.vho
junk+=$(project).srcs/sources_1/ip/clk_d100_100_200_125_25MHz/*.tcl
junk+=$(project).srcs/sources_1/ip/clk_d100_100_200_125_25MHz/*.ncf
junk+=$(project).srcs/sources_1/ip/clk_d100_100_200_125_25MHz/*.log
junk+=$(project).srcs/sources_1/ip/clk_d100_100_200_125_25MHz/doc
junk+=$(project).srcs/sources_1/ip/clk_d100_100_200_125_25MHz/sim
junk+=$(project).srcs/sources_1/ip/clk_d100_100_200_125_25MHz/synth
junk+=$(project).srcs/sources_1/ip/clk_d100_100_200_125_25MHz/clk_wiz_v5_3_1
# clk_d100_100_200_325_65MHz
junk+=$(project).srcs/sources_1/ip/clk_d100_100_200_325_65MHz/*.upgrade_log
junk+=$(project).srcs/sources_1/ip/clk_d100_100_200_325_65MHz/*.v
junk+=$(project).srcs/sources_1/ip/clk_d100_100_200_325_65MHz/*.vhdl
junk+=$(project).srcs/sources_1/ip/clk_d100_100_200_325_65MHz/*.dcp
junk+=$(project).srcs/sources_1/ip/clk_d100_100_200_325_65MHz/*.xml
junk+=$(project).srcs/sources_1/ip/clk_d100_100_200_325_65MHz/*.xdc
junk+=$(project).srcs/sources_1/ip/clk_d100_100_200_325_65MHz/*.veo
junk+=$(project).srcs/sources_1/ip/clk_d100_100_200_325_65MHz/*.vho
junk+=$(project).srcs/sources_1/ip/clk_d100_100_200_325_65MHz/*.tcl
junk+=$(project).srcs/sources_1/ip/clk_d100_100_200_325_65MHz/*.ncf
junk+=$(project).srcs/sources_1/ip/clk_d100_100_200_325_65MHz/*.log
junk+=$(project).srcs/sources_1/ip/clk_d100_100_200_325_65MHz/doc
junk+=$(project).srcs/sources_1/ip/clk_d100_100_200_325_65MHz/sim
junk+=$(project).srcs/sources_1/ip/clk_d100_100_200_325_65MHz/synth
junk+=$(project).srcs/sources_1/ip/clk_d100_100_200_325_65MHz/clk_wiz_v5_3_1
# clk_d100_100_200_40MHz
junk+=$(project).srcs/sources_1/ip/clk_d100_100_200_40MHz/*.upgrade_log
junk+=$(project).srcs/sources_1/ip/clk_d100_100_200_40MHz/*.v
junk+=$(project).srcs/sources_1/ip/clk_d100_100_200_40MHz/*.vhdl
junk+=$(project).srcs/sources_1/ip/clk_d100_100_200_40MHz/*.dcp
junk+=$(project).srcs/sources_1/ip/clk_d100_100_200_40MHz/*.xml
junk+=$(project).srcs/sources_1/ip/clk_d100_100_200_40MHz/*.xdc
junk+=$(project).srcs/sources_1/ip/clk_d100_100_200_40MHz/*.veo
junk+=$(project).srcs/sources_1/ip/clk_d100_100_200_40MHz/*.vho
junk+=$(project).srcs/sources_1/ip/clk_d100_100_200_40MHz/*.tcl
junk+=$(project).srcs/sources_1/ip/clk_d100_100_200_40MHz/*.ncf
junk+=$(project).srcs/sources_1/ip/clk_d100_100_200_40MHz/*.log
junk+=$(project).srcs/sources_1/ip/clk_d100_100_200_40MHz/doc
junk+=$(project).srcs/sources_1/ip/clk_d100_100_200_40MHz/sim
junk+=$(project).srcs/sources_1/ip/clk_d100_100_200_40MHz/synth
junk+=$(project).srcs/sources_1/ip/clk_d100_100_200_40MHz/clk_wiz_v5_3_1
# clk_d100_108_216_325_65MHz
junk+=$(project).srcs/sources_1/ip/clk_d100_108_216_325_65MHz/*.upgrade_log
junk+=$(project).srcs/sources_1/ip/clk_d100_108_216_325_65MHz/*.v
junk+=$(project).srcs/sources_1/ip/clk_d100_108_216_325_65MHz/*.vhdl
junk+=$(project).srcs/sources_1/ip/clk_d100_108_216_325_65MHz/*.dcp
junk+=$(project).srcs/sources_1/ip/clk_d100_108_216_325_65MHz/*.xml
junk+=$(project).srcs/sources_1/ip/clk_d100_108_216_325_65MHz/*.xdc
junk+=$(project).srcs/sources_1/ip/clk_d100_108_216_325_65MHz/*.veo
junk+=$(project).srcs/sources_1/ip/clk_d100_108_216_325_65MHz/*.vho
junk+=$(project).srcs/sources_1/ip/clk_d100_108_216_325_65MHz/*.tcl
junk+=$(project).srcs/sources_1/ip/clk_d100_108_216_325_65MHz/*.ncf
junk+=$(project).srcs/sources_1/ip/clk_d100_108_216_325_65MHz/*.log
junk+=$(project).srcs/sources_1/ip/clk_d100_108_216_325_65MHz/.Xil
junk+=$(project).srcs/sources_1/ip/clk_d100_108_216_325_65MHz/doc
junk+=$(project).srcs/sources_1/ip/clk_d100_108_216_325_65MHz/sim
junk+=$(project).srcs/sources_1/ip/clk_d100_108_216_325_65MHz/synth
junk+=$(project).srcs/sources_1/ip/clk_d100_108_216_325_65MHz/clk_wiz_v5_3_1
# clk_d100_108_216_541MHz
junk+=$(project).srcs/sources_1/ip/clk_d100_108_216_541MHz/*.upgrade_log
junk+=$(project).srcs/sources_1/ip/clk_d100_108_216_541MHz/*.v
junk+=$(project).srcs/sources_1/ip/clk_d100_108_216_541MHz/*.vhdl
junk+=$(project).srcs/sources_1/ip/clk_d100_108_216_541MHz/*.dcp
junk+=$(project).srcs/sources_1/ip/clk_d100_108_216_541MHz/*.xml
junk+=$(project).srcs/sources_1/ip/clk_d100_108_216_541MHz/*.xdc
junk+=$(project).srcs/sources_1/ip/clk_d100_108_216_541MHz/*.veo
junk+=$(project).srcs/sources_1/ip/clk_d100_108_216_541MHz/*.vho
junk+=$(project).srcs/sources_1/ip/clk_d100_108_216_541MHz/*.tcl
junk+=$(project).srcs/sources_1/ip/clk_d100_108_216_541MHz/*.ncf
junk+=$(project).srcs/sources_1/ip/clk_d100_108_216_541MHz/*.log
junk+=$(project).srcs/sources_1/ip/clk_d100_108_216_541MHz/.Xil
junk+=$(project).srcs/sources_1/ip/clk_d100_108_216_541MHz/doc
junk+=$(project).srcs/sources_1/ip/clk_d100_108_216_541MHz/sim
junk+=$(project).srcs/sources_1/ip/clk_d100_108_216_541MHz/synth
junk+=$(project).srcs/sources_1/ip/clk_d100_108_216_541MHz/clk_wiz_v5_3_1


include ../../include/vivado.mk
