-- VHDL netlist generated by SCUBA Diamond_1.2_Production (92)
-- Module  Version: 5.2
--/usr/local/diamond/1.2/ispfpga/bin/lin/scuba -w -n pll -lang vhdl -synth synplify -arch mg5a00 -type pll -fin 25 -phase_cntl STATIC -fclkop 325 -fclkop_tol 0.0 -fb_mode INTERNAL -noclkos -fclkok 81.25 -fclkok_tol 0.0 -norst -e 

-- Fri Jul  8 14:06:46 2011

library IEEE;
use IEEE.std_logic_1164.all;
-- synopsys translate_off
library xp2;
use xp2.components.all;
-- synopsys translate_on

entity pll_81_325 is
    port (
        CLK: in std_logic; 
        CLKOP: out std_logic; 
        CLKOK: out std_logic; 
        CLKOK2: out std_logic; 
        LOCK: out std_logic);
 attribute dont_touch : boolean;
 attribute dont_touch of pll_81_325 : entity is true;
end pll_81_325;

architecture Structure of pll_81_325 is

    -- internal signal declarations
    signal CLKOP_t: std_logic;
    signal CLKFB_t: std_logic;
    signal scuba_vlo: std_logic;

    -- local component declarations
    component VLO
        port (Z: out std_logic);
    end component;
    component EHXPLLE1
    -- synopsys translate_off
        generic (CLKOS_TRIM_DELAY : in Integer; 
                CLKOS_TRIM_POL : in String; 
                CLKOP_TRIM_DELAY : in Integer; 
                CLKOP_TRIM_POL : in String; CLKOK_BYPASS : in String; 
                CLKOS_BYPASS : in String; CLKOP_BYPASS : in String; 
                DUTY : in Integer; PHASEADJ : in String; 
                PHASE_CNTL : in String; CLKOK_DIV : in Integer; 
                CLKFB_DIV : in Integer; CLKOP_DIV : in Integer; 
                CLKI_DIV : in Integer);
    -- synopsys translate_on
        port (CLKI: in std_logic; CLKFB: in std_logic; RST: in std_logic; 
            RSTK: in std_logic; WRDEL: in std_logic; DRPAI3: in std_logic; 
            DRPAI2: in std_logic; DRPAI1: in std_logic; DRPAI0: in std_logic; 
            DFPAI3: in std_logic; DFPAI2: in std_logic; DFPAI1: in std_logic; 
            DFPAI0: in std_logic; PWD: in std_logic; CLKOP: out std_logic; 
            CLKOS: out std_logic; CLKOK: out std_logic; CLKOK2: out std_logic; 
            LOCK: out std_logic; CLKINTFB: out std_logic);
    end component;
    attribute FREQUENCY_PIN_CLKOP : string; 
    attribute FREQUENCY_PIN_CLKI : string; 
    attribute FREQUENCY_PIN_CLKOK : string; 
    attribute FREQUENCY_PIN_CLKOP of PLLInst_0 : label is "325.000000";
    attribute FREQUENCY_PIN_CLKI of PLLInst_0 : label is "25.000000";
    attribute FREQUENCY_PIN_CLKOK of PLLInst_0 : label is "81.250000";

begin
    -- component instantiation statements
    scuba_vlo_inst: VLO
        port map (Z=>scuba_vlo);

    PLLInst_0: EHXPLLE1
        -- synopsys translate_off
        generic map (CLKOK_BYPASS=> "DISABLED", CLKOS_BYPASS=> "DISABLED", 
        CLKOP_BYPASS=> "DISABLED", CLKOS_TRIM_DELAY=>  0, CLKOS_TRIM_POL=> "RISING", 
        CLKOP_TRIM_DELAY=>  0, CLKOP_TRIM_POL=> "FALLING", PHASE_CNTL=> "STATIC", 
        DUTY=>  8, PHASEADJ=> "0.0", CLKOK_DIV=>  4, CLKOP_DIV=>  2, 
        CLKFB_DIV=>  13, CLKI_DIV=>  1)
        -- synopsys translate_on
        port map (CLKI=>CLK, CLKFB=>CLKFB_t, RST=>scuba_vlo, 
            RSTK=>scuba_vlo, WRDEL=>scuba_vlo, DRPAI3=>scuba_vlo, 
            DRPAI2=>scuba_vlo, DRPAI1=>scuba_vlo, DRPAI0=>scuba_vlo, 
            DFPAI3=>scuba_vlo, DFPAI2=>scuba_vlo, DFPAI1=>scuba_vlo, 
            DFPAI0=>scuba_vlo, PWD=>scuba_vlo, CLKOP=>CLKOP_t, 
            CLKOS=>open, CLKOK=>CLKOK, CLKOK2=>CLKOK2, LOCK=>LOCK, 
            CLKINTFB=>CLKFB_t);

    CLKOP <= CLKOP_t;
end Structure;

-- synopsys translate_off
library xp2;
configuration Structure_CON of pll_81_325 is
    for Structure
        for all:VLO use entity xp2.VLO(V); end for;
        for all:EHXPLLE1 use entity xp2.EHXPLLE1(V); end for;
    end for;
end Structure_CON;

-- synopsys translate_on
