BOARD = ulx3s
BOARD_VERSION = v20

# FPGA_SIZE 12/25/45/85
FPGA_SIZE = 45

# bitstream file prefix
BITSTREAM_PREFIX = f32c_$(BOARD)_$(BOARD_VERSION)_$(FPGA_SIZE)k_pix8bpp640x480oledspi_100mhz

include ../../include/ulx3s.mk
