# Generated by makeXDC.ulp developed by Sven Raiser, Tuebingen, Germany
#
# Board:     FFM-A7100-v0r0.brd
# Part Name: FPGA
# Part pkg:  BGA484
# Created:   09.10.2017 23:13:01

set_property CFGBVS VCCO [current_design]
#where value1 is either VCCO or GND

set_property CONFIG_VOLTAGE 3.3 [current_design]
#where value2 is the voltage provided to configuration bank 0

#
#	Clocks & Reset & LEDS
#

set_property -dict {PACKAGE_PIN T4 IOSTANDARD LVDS_25} [get_ports i_100MHz_N]
set_property -dict {PACKAGE_PIN R4 IOSTANDARD LVDS_25} [get_ports i_100MHz_P]
set_property -dict {PACKAGE_PIN V13 IOSTANDARD LVTTL} [get_ports PON_RESET_N]

#
#	UART3
#

set_property -dict {PACKAGE_PIN W9 IOSTANDARD LVTTL} [get_ports UART3_RXD]
set_property -dict {PACKAGE_PIN V8 IOSTANDARD LVTTL} [get_ports UART3_TXD]

#
#	SDRAM
#

#set_property -dict {PACKAGE_PIN AA16 IOSTANDARD LVTTL} [get_ports {DR_A[0]}]
#set_property -dict {PACKAGE_PIN AA15 IOSTANDARD LVTTL} [get_ports {DR_A[1]}]
#set_property -dict {PACKAGE_PIN AB17 IOSTANDARD LVTTL} [get_ports {DR_A[2]}]
#set_property -dict {PACKAGE_PIN Y16 IOSTANDARD LVTTL} [get_ports {DR_A[3]}]
#set_property -dict {PACKAGE_PIN Y17 IOSTANDARD LVTTL} [get_ports {DR_A[4]}]
#set_property -dict {PACKAGE_PIN W16 IOSTANDARD LVTTL} [get_ports {DR_A[5]}]
#set_property -dict {PACKAGE_PIN Y11 IOSTANDARD LVTTL} [get_ports {DR_A[6]}]
#set_property -dict {PACKAGE_PIN V15 IOSTANDARD LVTTL} [get_ports {DR_A[7]}]
#set_property -dict {PACKAGE_PIN W15 IOSTANDARD LVTTL} [get_ports {DR_A[8]}]
#set_property -dict {PACKAGE_PIN AA11 IOSTANDARD LVTTL} [get_ports {DR_A[9]}]
#set_property -dict {PACKAGE_PIN Y14 IOSTANDARD LVTTL} [get_ports {DR_A[10]}]
#set_property -dict {PACKAGE_PIN AB16 IOSTANDARD LVTTL} [get_ports {DR_A[11]}]
#set_property -dict {PACKAGE_PIN Y12 IOSTANDARD LVTTL} [get_ports {DR_A[12]}]
#set_property -dict {PACKAGE_PIN AA14 IOSTANDARD LVTTL} [get_ports DR_BA0]
#set_property -dict {PACKAGE_PIN AB15 IOSTANDARD LVTTL} [get_ports DR_BA1]
#set_property -dict {PACKAGE_PIN AA13 IOSTANDARD LVTTL} [get_ports DR_CAS_N]
#set_property -dict {PACKAGE_PIN Y13 IOSTANDARD LVTTL} [get_ports DR_CKE]
#set_property -dict {PACKAGE_PIN W14 IOSTANDARD LVTTL} [get_ports DR_CLK]
#set_property -dict {PACKAGE_PIN AB12 IOSTANDARD LVTTL} [get_ports DR_CS_N]
#set_property -dict {PACKAGE_PIN AB22 IOSTANDARD LVTTL} [get_ports {DR_D[0]}]
#set_property -dict {PACKAGE_PIN Y21 IOSTANDARD LVTTL} [get_ports {DR_D[1]}]
#set_property -dict {PACKAGE_PIN AB21 IOSTANDARD LVTTL} [get_ports {DR_D[2]}]
#set_property -dict {PACKAGE_PIN Y22 IOSTANDARD LVTTL} [get_ports {DR_D[3]}]
#set_property -dict {PACKAGE_PIN AA21 IOSTANDARD LVTTL} [get_ports {DR_D[4]}]
#set_property -dict {PACKAGE_PIN W22 IOSTANDARD LVTTL} [get_ports {DR_D[5]}]
#set_property -dict {PACKAGE_PIN W21 IOSTANDARD LVTTL} [get_ports {DR_D[6]}]
#set_property -dict {PACKAGE_PIN W20 IOSTANDARD LVTTL} [get_ports {DR_D[7]}]
#set_property -dict {PACKAGE_PIN T18 IOSTANDARD LVTTL} [get_ports {DR_D[8]}]
#set_property -dict {PACKAGE_PIN V18 IOSTANDARD LVTTL} [get_ports {DR_D[9]}]
#set_property -dict {PACKAGE_PIN U18 IOSTANDARD LVTTL} [get_ports {DR_D[10]}]
#set_property -dict {PACKAGE_PIN W19 IOSTANDARD LVTTL} [get_ports {DR_D[11]}]
#set_property -dict {PACKAGE_PIN V19 IOSTANDARD LVTTL} [get_ports {DR_D[12]}]
#set_property -dict {PACKAGE_PIN AA20 IOSTANDARD LVTTL} [get_ports {DR_D[13]}]
#set_property -dict {PACKAGE_PIN Y19 IOSTANDARD LVTTL} [get_ports {DR_D[14]}]
#set_property -dict {PACKAGE_PIN AB20 IOSTANDARD LVTTL} [get_ports {DR_D[15]}]
#set_property -dict {PACKAGE_PIN U22 IOSTANDARD LVTTL} [get_ports {DR_D[16]}]
#set_property -dict {PACKAGE_PIN U20 IOSTANDARD LVTTL} [get_ports {DR_D[17]}]
#set_property -dict {PACKAGE_PIN U21 IOSTANDARD LVTTL} [get_ports {DR_D[18]}]
#set_property -dict {PACKAGE_PIN R19 IOSTANDARD LVTTL} [get_ports {DR_D[19]}]
#set_property -dict {PACKAGE_PIN T21 IOSTANDARD LVTTL} [get_ports {DR_D[20]}]
#set_property -dict {PACKAGE_PIN P19 IOSTANDARD LVTTL} [get_ports {DR_D[21]}]
#set_property -dict {PACKAGE_PIN T20 IOSTANDARD LVTTL} [get_ports {DR_D[22]}]
#set_property -dict {PACKAGE_PIN P20 IOSTANDARD LVTTL} [get_ports {DR_D[23]}]
#set_property -dict {PACKAGE_PIN P17 IOSTANDARD LVTTL} [get_ports {DR_D[24]}]
#set_property -dict {PACKAGE_PIN U17 IOSTANDARD LVTTL} [get_ports {DR_D[25]}]
#set_property -dict {PACKAGE_PIN R17 IOSTANDARD LVTTL} [get_ports {DR_D[26]}]
#set_property -dict {PACKAGE_PIN W17 IOSTANDARD LVTTL} [get_ports {DR_D[27]}]
#set_property -dict {PACKAGE_PIN V17 IOSTANDARD LVTTL} [get_ports {DR_D[28]}]
#set_property -dict {PACKAGE_PIN AA18 IOSTANDARD LVTTL} [get_ports {DR_D[29]}]
#set_property -dict {PACKAGE_PIN Y18 IOSTANDARD LVTTL} [get_ports {DR_D[30]}]
#set_property -dict {PACKAGE_PIN AA19 IOSTANDARD LVTTL} [get_ports {DR_D[31]}]
#set_property -dict {PACKAGE_PIN V22 IOSTANDARD LVTTL} [get_ports DR_DQM0]
#set_property -dict {PACKAGE_PIN R18 IOSTANDARD LVTTL} [get_ports DR_DQM1]
#set_property -dict {PACKAGE_PIN V20 IOSTANDARD LVTTL} [get_ports DR_DQM2]
#set_property -dict {PACKAGE_PIN AB18 IOSTANDARD LVTTL} [get_ports DR_DQM3]
#set_property -dict {PACKAGE_PIN AB13 IOSTANDARD LVTTL} [get_ports DR_RAS_N]
#set_property -dict {PACKAGE_PIN AB11 IOSTANDARD LVTTL} [get_ports DR_WE_N]


#
#	DDR3 (do not enable this because pins will be named and enumerated by MIG)
#
#set_property -dict {PACKAGE_PIN A1 IOSTANDARD LVTTL} [get_ports {DDR3_A[0]}]
#set_property -dict {PACKAGE_PIN B2 IOSTANDARD LVTTL} [get_ports {DDR3_A[1]}]
#set_property -dict {PACKAGE_PIN D2 IOSTANDARD LVTTL} [get_ports {DDR3_A[2]}]
#set_property -dict {PACKAGE_PIN H3 IOSTANDARD LVTTL} [get_ports {DDR3_A[3]}]
#set_property -dict {PACKAGE_PIN G2 IOSTANDARD LVTTL} [get_ports {DDR3_A[4]}]
#set_property -dict {PACKAGE_PIN F3 IOSTANDARD LVTTL} [get_ports {DDR3_A[5]}]
#set_property -dict {PACKAGE_PIN H2 IOSTANDARD LVTTL} [get_ports {DDR3_A[6]}]
#set_property -dict {PACKAGE_PIN B1 IOSTANDARD LVTTL} [get_ports {DDR3_A[7]}]
#set_property -dict {PACKAGE_PIN E1 IOSTANDARD LVTTL} [get_ports {DDR3_A[8]}]
#set_property -dict {PACKAGE_PIN E2 IOSTANDARD LVTTL} [get_ports {DDR3_A[9]}]
#set_property -dict {PACKAGE_PIN H5 IOSTANDARD LVTTL} [get_ports {DDR3_A[10]}]
#set_property -dict {PACKAGE_PIN D1 IOSTANDARD LVTTL} [get_ports {DDR3_A[11]}]
#set_property -dict {PACKAGE_PIN J5 IOSTANDARD LVTTL} [get_ports {DDR3_A[12]}]
#set_property -dict {PACKAGE_PIN C2 IOSTANDARD LVTTL} [get_ports {DDR3_A[13]}]
#set_property -dict {PACKAGE_PIN F1 IOSTANDARD LVTTL} [get_ports {DDR3_BA[0]}]
#set_property -dict {PACKAGE_PIN J2 IOSTANDARD LVTTL} [get_ports {DDR3_BA[1]}]
#set_property -dict {PACKAGE_PIN G1 IOSTANDARD LVTTL} [get_ports {DDR3_BA[2]}]
#set_property -dict {PACKAGE_PIN G4 IOSTANDARD LVTTL} [get_ports DDR3_CAS_N]
#set_property -dict {PACKAGE_PIN K2 IOSTANDARD LVTTL} [get_ports DDR3_CKE]
#set_property -dict {PACKAGE_PIN J1 IOSTANDARD LVTTL} [get_ports DDR3_CK_N]
#set_property -dict {PACKAGE_PIN K1 IOSTANDARD LVTTL} [get_ports DDR3_CK_P]
#set_property -dict {PACKAGE_PIN J6 IOSTANDARD LVTTL} [get_ports {DDR3_DM[0]}]
#set_property -dict {PACKAGE_PIN N4 IOSTANDARD LVTTL} [get_ports {DDR3_DM[1]}]
#set_property -dict {PACKAGE_PIN K6 IOSTANDARD LVTTL} [get_ports {DDR3_DQ[0]}]
#set_property -dict {PACKAGE_PIN L5 IOSTANDARD LVTTL} [get_ports {DDR3_DQ[1]}]
#set_property -dict {PACKAGE_PIN L3 IOSTANDARD LVTTL} [get_ports {DDR3_DQ[2]}]
#set_property -dict {PACKAGE_PIN L4 IOSTANDARD LVTTL} [get_ports {DDR3_DQ[3]}]
#set_property -dict {PACKAGE_PIN K4 IOSTANDARD LVTTL} [get_ports {DDR3_DQ[4]}]
#set_property -dict {PACKAGE_PIN M2 IOSTANDARD LVTTL} [get_ports {DDR3_DQ[5]}]
#set_property -dict {PACKAGE_PIN J4 IOSTANDARD LVTTL} [get_ports {DDR3_DQ[6]}]
#set_property -dict {PACKAGE_PIN K3 IOSTANDARD LVTTL} [get_ports {DDR3_DQ[7]}]
#set_property -dict {PACKAGE_PIN R1 IOSTANDARD LVTTL} [get_ports {DDR3_DQ[8]}]
#set_property -dict {PACKAGE_PIN N5 IOSTANDARD LVTTL} [get_ports {DDR3_DQ[9]}]
#set_property -dict {PACKAGE_PIN P1 IOSTANDARD LVTTL} [get_ports {DDR3_DQ[10]}]
#set_property -dict {PACKAGE_PIN P6 IOSTANDARD LVTTL} [get_ports {DDR3_DQ[11]}]
#set_property -dict {PACKAGE_PIN N2 IOSTANDARD LVTTL} [get_ports {DDR3_DQ[12]}]
#set_property -dict {PACKAGE_PIN P2 IOSTANDARD LVTTL} [get_ports {DDR3_DQ[13]}]
#set_property -dict {PACKAGE_PIN M5 IOSTANDARD LVTTL} [get_ports {DDR3_DQ[14]}]
#set_property -dict {PACKAGE_PIN M6 IOSTANDARD LVTTL} [get_ports {DDR3_DQ[15]}]
#set_property -dict {PACKAGE_PIN L1 IOSTANDARD LVTTL} [get_ports {DDR3_DQS_N[0]}]
#set_property -dict {PACKAGE_PIN P4 IOSTANDARD LVTTL} [get_ports {DDR3_DQS_N[1]}]
#set_property -dict {PACKAGE_PIN M1 IOSTANDARD LVTTL} [get_ports {DDR3_DQS_P[0]}]
#set_property -dict {PACKAGE_PIN P5 IOSTANDARD LVTTL} [get_ports {DDR3_DQS_P[1]}]
#set_property -dict {PACKAGE_PIN F4 IOSTANDARD LVTTL} [get_ports DDR3_ODT]
#set_property -dict {PACKAGE_PIN H4 IOSTANDARD LVTTL} [get_ports DDR3_RAS_N]
#set_property -dict {PACKAGE_PIN L6 IOSTANDARD LVTTL} [get_ports DDR3_RESET_N]
#set_property -dict {PACKAGE_PIN G3 IOSTANDARD LVTTL} [get_ports DDR3_WE_N]

#
#	Digital Video 0, out on tms141
#

set_property -dict {PACKAGE_PIN AB2 IOSTANDARD TMDS_33} [get_ports VID_CLK_N]
set_property -dict {PACKAGE_PIN AB3 IOSTANDARD TMDS_33} [get_ports VID_CLK_P]
set_property -dict {PACKAGE_PIN AB5 IOSTANDARD TMDS_33} [get_ports VID_D_N[0]]
set_property -dict {PACKAGE_PIN AA5 IOSTANDARD TMDS_33} [get_ports VID_D_P[0]]
set_property -dict {PACKAGE_PIN AB6 IOSTANDARD TMDS_33} [get_ports VID_D_N[1]]
set_property -dict {PACKAGE_PIN AB7 IOSTANDARD TMDS_33} [get_ports VID_D_P[1]]
set_property -dict {PACKAGE_PIN AB8 IOSTANDARD TMDS_33} [get_ports VID_D_N[2]]
set_property -dict {PACKAGE_PIN AA8 IOSTANDARD TMDS_33} [get_ports VID_D_P[2]]
#set_property -dict {PACKAGE_PIN U5 IOSTANDARD LVTTL} [get_ports VID_RSCL]
#set_property -dict {PACKAGE_PIN U3 IOSTANDARD LVTTL} [get_ports VID_RSDA]
#set_property -dict {PACKAGE_PIN T3 IOSTANDARD LVTTL} [get_ports VID_SRC]

#
#	experimental Dig Video 2
#


#
#	Ethernet Phy
#

#set_property -dict {PACKAGE_PIN U7 IOSTANDARD LVTTL} [get_ports ETH_CRS]
#set_property -dict {PACKAGE_PIN Y6 IOSTANDARD LVTTL} [get_ports ETH_MDC]
#set_property -dict {PACKAGE_PIN Y4 IOSTANDARD LVTTL} [get_ports ETH_MDIO]
#set_property -dict {PACKAGE_PIN Y7 IOSTANDARD LVTTL} [get_ports ETH_RXD_0]
#set_property -dict {PACKAGE_PIN W7 IOSTANDARD LVTTL} [get_ports ETH_RXD_1]
#set_property -dict {PACKAGE_PIN Y8 IOSTANDARD LVTTL} [get_ports ETH_RXD_2]
#set_property -dict {PACKAGE_PIN V7 IOSTANDARD LVTTL} [get_ports ETH_RXD_3]
#set_property -dict {PACKAGE_PIN U6 IOSTANDARD LVTTL} [get_ports ETH_RX_CLK]
#set_property -dict {PACKAGE_PIN Y3 IOSTANDARD LVTTL} [get_ports ETH_TXD_0]
#set_property -dict {PACKAGE_PIN W5 IOSTANDARD LVTTL} [get_ports ETH_TXD_1]
#set_property -dict {PACKAGE_PIN AA3 IOSTANDARD LVTTL} [get_ports ETH_TXD_2]
#set_property -dict {PACKAGE_PIN W6 IOSTANDARD LVTTL} [get_ports ETH_TXD_3]
#set_property -dict {PACKAGE_PIN T5 IOSTANDARD LVTTL} [get_ports ETH_TX_CLK]
#set_property -dict {PACKAGE_PIN W4 IOSTANDARD LVTTL} [get_ports ETH_TX_EN]


#
#	FIOs
#


set_property -dict {PACKAGE_PIN M21 IOSTANDARD LVTTL} [get_ports FIO[0]]
set_property -dict {PACKAGE_PIN M22 IOSTANDARD LVTTL} [get_ports FIO[1]]
set_property -dict {PACKAGE_PIN L21 IOSTANDARD LVTTL} [get_ports FIO[2]]
set_property -dict {PACKAGE_PIN N18 IOSTANDARD LVTTL} [get_ports FIO[3]]
set_property -dict {PACKAGE_PIN N19 IOSTANDARD LVTTL} [get_ports FIO[4]]
set_property -dict {PACKAGE_PIN N20 IOSTANDARD LVTTL} [get_ports FIO[5]]
set_property -dict {PACKAGE_PIN M20 IOSTANDARD LVTTL} [get_ports FIO[6]]
set_property -dict {PACKAGE_PIN M18 IOSTANDARD LVTTL} [get_ports FIO[7]]
set_property -dict {PACKAGE_PIN L18 IOSTANDARD LVTTL} [get_ports FIO[8]]
set_property -dict {PACKAGE_PIN L19 IOSTANDARD LVTTL} [get_ports FIO[9]]
set_property -dict {PACKAGE_PIN K18 IOSTANDARD LVTTL} [get_ports FIO[10]]
set_property -dict {PACKAGE_PIN K19 IOSTANDARD LVTTL} [get_ports FIO[11]]
set_property -dict {PACKAGE_PIN J19 IOSTANDARD LVTTL} [get_ports FIO[12]]
set_property -dict {PACKAGE_PIN L20 IOSTANDARD LVTTL} [get_ports FIO[13]]
set_property -dict {PACKAGE_PIN H18 IOSTANDARD LVTTL} [get_ports FIO[14]]
set_property -dict {PACKAGE_PIN K22 IOSTANDARD LVTTL} [get_ports FIO[15]]
set_property -dict {PACKAGE_PIN H19 IOSTANDARD LVTTL} [get_ports FIO[16]]
set_property -dict {PACKAGE_PIN K21 IOSTANDARD LVTTL} [get_ports FIO[17]]
set_property -dict {PACKAGE_PIN G18 IOSTANDARD LVTTL} [get_ports FIO[18]]
set_property -dict {PACKAGE_PIN J22 IOSTANDARD LVTTL} [get_ports FIO[19]]
set_property -dict {PACKAGE_PIN F19 IOSTANDARD LVTTL} [get_ports FIO[20]]
set_property -dict {PACKAGE_PIN J21 IOSTANDARD LVTTL} [get_ports FIO[21]]
set_property -dict {PACKAGE_PIN D20 IOSTANDARD LVTTL} [get_ports FIO[22]]
set_property -dict {PACKAGE_PIN H22 IOSTANDARD LVTTL} [get_ports FIO[23]]
set_property -dict {PACKAGE_PIN C19 IOSTANDARD LVTTL} [get_ports FIO[24]]
set_property -dict {PACKAGE_PIN M17 IOSTANDARD LVTTL} [get_ports FIO[25]]
set_property -dict {PACKAGE_PIN E18 IOSTANDARD LVTTL} [get_ports FIO[26]]
set_property -dict {PACKAGE_PIN K16 IOSTANDARD LVTTL} [get_ports FIO[27]]
set_property -dict {PACKAGE_PIN E17 IOSTANDARD LVTTL} [get_ports FIO[28]]
set_property -dict {PACKAGE_PIN J17 IOSTANDARD LVTTL} [get_ports FIO[29]]
set_property -dict {PACKAGE_PIN D17 IOSTANDARD LVTTL} [get_ports FIO[30]]
set_property -dict {PACKAGE_PIN G17 IOSTANDARD LVTTL} [get_ports FIO[31]]
set_property -dict {PACKAGE_PIN C17 IOSTANDARD LVTTL} [get_ports FIO[32]]
set_property -dict {PACKAGE_PIN G15 IOSTANDARD LVTTL} [get_ports FIO[33]]
set_property -dict {PACKAGE_PIN D16 IOSTANDARD LVTTL} [get_ports FIO[34]]
set_property -dict {PACKAGE_PIN F16 IOSTANDARD LVTTL} [get_ports FIO[35]]
set_property -dict {PACKAGE_PIN D15 IOSTANDARD LVTTL} [get_ports FIO[36]]
set_property -dict {PACKAGE_PIN E16 IOSTANDARD LVTTL} [get_ports FIO[37]]
set_property -dict {PACKAGE_PIN C15 IOSTANDARD LVTTL} [get_ports FIO[38]]
set_property -dict {PACKAGE_PIN F15 IOSTANDARD LVTTL} [get_ports FIO[39]]
set_property -dict {PACKAGE_PIN D14 IOSTANDARD LVTTL} [get_ports FIO[40]]
set_property -dict {PACKAGE_PIN F14 IOSTANDARD LVTTL} [get_ports FIO[41]]
set_property -dict {PACKAGE_PIN C14 IOSTANDARD LVTTL} [get_ports FIO[42]]
set_property -dict {PACKAGE_PIN F13 IOSTANDARD LVTTL} [get_ports FIO[43]]
set_property -dict {PACKAGE_PIN E14 IOSTANDARD LVTTL} [get_ports FIO[44]]
set_property -dict {PACKAGE_PIN G13 IOSTANDARD LVTTL} [get_ports FIO[45]]
set_property -dict {PACKAGE_PIN E13 IOSTANDARD LVTTL} [get_ports FIO[46]]
set_property -dict {PACKAGE_PIN H13 IOSTANDARD LVTTL} [get_ports FIO[47]]
set_property -dict {PACKAGE_PIN C13 IOSTANDARD LVTTL} [get_ports FIO[48]]
set_property -dict {PACKAGE_PIN M15 IOSTANDARD LVTTL} [get_ports FIO[49]]
set_property -dict {PACKAGE_PIN L14 IOSTANDARD LVTTL} [get_ports FIO[50]]
set_property -dict {PACKAGE_PIN L15 IOSTANDARD LVTTL} [get_ports FIO[51]]
set_property -dict {PACKAGE_PIN K14 IOSTANDARD LVTTL} [get_ports FIO[52]]
set_property -dict {PACKAGE_PIN J16 IOSTANDARD LVTTL} [get_ports FIO[53]]
set_property -dict {PACKAGE_PIN J15 IOSTANDARD LVTTL} [get_ports FIO[54]]
set_property -dict {PACKAGE_PIN J14 IOSTANDARD LVTTL} [get_ports FIO[55]]
set_property -dict {PACKAGE_PIN H15 IOSTANDARD LVTTL} [get_ports FIO[56]]
set_property -dict {PACKAGE_PIN H14 IOSTANDARD LVTTL} [get_ports FIO[57]]
set_property -dict {PACKAGE_PIN K13 IOSTANDARD LVTTL} [get_ports FIO[58]]
set_property -dict {PACKAGE_PIN L13 IOSTANDARD LVTTL} [get_ports FIO[59]]
set_property -dict {PACKAGE_PIN J20 IOSTANDARD LVTTL} [get_ports FIO[60]]
set_property -dict {PACKAGE_PIN G22 IOSTANDARD LVTTL} [get_ports FIO[61]]
set_property -dict {PACKAGE_PIN H20 IOSTANDARD LVTTL} [get_ports FIO[62]]
set_property -dict {PACKAGE_PIN G21 IOSTANDARD LVTTL} [get_ports FIO[63]]
set_property -dict {PACKAGE_PIN G20 IOSTANDARD LVTTL} [get_ports FIO[64]]
set_property -dict {PACKAGE_PIN F21 IOSTANDARD LVTTL} [get_ports FIO[65]]
set_property -dict {PACKAGE_PIN F20 IOSTANDARD LVTTL} [get_ports FIO[66]]
set_property -dict {PACKAGE_PIN E22 IOSTANDARD LVTTL} [get_ports FIO[67]]
set_property -dict {PACKAGE_PIN F18 IOSTANDARD LVTTL} [get_ports FIO[68]]
set_property -dict {PACKAGE_PIN E21 IOSTANDARD LVTTL} [get_ports FIO[69]]
set_property -dict {PACKAGE_PIN E19 IOSTANDARD LVTTL} [get_ports FIO[70]]
set_property -dict {PACKAGE_PIN D22 IOSTANDARD LVTTL} [get_ports FIO[71]]
set_property -dict {PACKAGE_PIN D19 IOSTANDARD LVTTL} [get_ports FIO[72]]
set_property -dict {PACKAGE_PIN M16 IOSTANDARD LVTTL} [get_ports FIO[73]]
set_property -dict {PACKAGE_PIN L16 IOSTANDARD LVTTL} [get_ports FIO[74]]
set_property -dict {PACKAGE_PIN D21 IOSTANDARD LVTTL} [get_ports FIO[75]]
set_property -dict {PACKAGE_PIN K17 IOSTANDARD LVTTL} [get_ports FIO[76]]
set_property -dict {PACKAGE_PIN C22 IOSTANDARD LVTTL} [get_ports FIO[77]]
set_property -dict {PACKAGE_PIN H17 IOSTANDARD LVTTL} [get_ports FIO[78]]
set_property -dict {PACKAGE_PIN B22 IOSTANDARD LVTTL} [get_ports FIO[79]]
set_property -dict {PACKAGE_PIN G16 IOSTANDARD LVTTL} [get_ports FIO[80]]
set_property -dict {PACKAGE_PIN B21 IOSTANDARD LVTTL} [get_ports FIO[81]]
set_property -dict {PACKAGE_PIN A21 IOSTANDARD LVTTL} [get_ports FIO[82]]
set_property -dict {PACKAGE_PIN C20 IOSTANDARD LVTTL} [get_ports FIO[83]]
set_property -dict {PACKAGE_PIN A20 IOSTANDARD LVTTL} [get_ports FIO[84]]
set_property -dict {PACKAGE_PIN B20 IOSTANDARD LVTTL} [get_ports FIO[85]]
set_property -dict {PACKAGE_PIN C18 IOSTANDARD LVTTL} [get_ports FIO[86]]
set_property -dict {PACKAGE_PIN A19 IOSTANDARD LVTTL} [get_ports FIO[87]]
set_property -dict {PACKAGE_PIN B18 IOSTANDARD LVTTL} [get_ports FIO[88]]
set_property -dict {PACKAGE_PIN A18 IOSTANDARD LVTTL} [get_ports FIO[89]]
set_property -dict {PACKAGE_PIN A16 IOSTANDARD LVTTL} [get_ports FIO[90]]
set_property -dict {PACKAGE_PIN B17 IOSTANDARD LVTTL} [get_ports FIO[91]]
set_property -dict {PACKAGE_PIN A15 IOSTANDARD LVTTL} [get_ports FIO[92]]
set_property -dict {PACKAGE_PIN B16 IOSTANDARD LVTTL} [get_ports FIO[93]]
set_property -dict {PACKAGE_PIN A14 IOSTANDARD LVTTL} [get_ports FIO[94]]
set_property -dict {PACKAGE_PIN B15 IOSTANDARD LVTTL} [get_ports FIO[95]]
set_property -dict {PACKAGE_PIN A13 IOSTANDARD LVTTL} [get_ports FIO[96]]
set_property -dict {PACKAGE_PIN B13 IOSTANDARD LVTTL} [get_ports FIO[97]]

#
#	SD-Card
#


#set_property -dict {PACKAGE_PIN W12 IOSTANDARD LVTTL} [get_ports SD_M_CDET]
set_property -dict {PACKAGE_PIN W11 IOSTANDARD LVTTL} [get_ports SD_M_CLK]
set_property -dict {PACKAGE_PIN AA10 IOSTANDARD LVTTL} [get_ports SD_M_CMD]
set_property -dict {PACKAGE_PIN AA9 IOSTANDARD LVTTL} [get_ports SD_M_D0]
#set_property -dict {PACKAGE_PIN AB10 IOSTANDARD LVTTL} [get_ports SD_M_D1]
#set_property -dict {PACKAGE_PIN W10 IOSTANDARD LVTTL} [get_ports SD_M_D2]
set_property -dict {PACKAGE_PIN V10 IOSTANDARD LVTTL} [get_ports SD_M_D3]

#
#	USB Phy
#

#set_property -dict {PACKAGE_PIN R2 IOSTANDARD LVTTL} [get_ports USB_CLK]
#set_property -dict {PACKAGE_PIN V9 IOSTANDARD LVTTL} [get_ports USB_DIR]
#set_property -dict {PACKAGE_PIN T1 IOSTANDARD LVTTL} [get_ports USB_D_0]
#set_property -dict {PACKAGE_PIN U1 IOSTANDARD LVTTL} [get_ports USB_D_1]
#set_property -dict {PACKAGE_PIN U2 IOSTANDARD LVTTL} [get_ports USB_D_2]
#set_property -dict {PACKAGE_PIN V2 IOSTANDARD LVTTL} [get_ports USB_D_3]
#set_property -dict {PACKAGE_PIN W1 IOSTANDARD LVTTL} [get_ports USB_D_4]
#set_property -dict {PACKAGE_PIN Y1 IOSTANDARD LVTTL} [get_ports USB_D_5]
#set_property -dict {PACKAGE_PIN AA4 IOSTANDARD LVTTL} [get_ports USB_D_6]
#set_property -dict {PACKAGE_PIN AA6 IOSTANDARD LVTTL} [get_ports USB_D_7]
#set_property -dict {PACKAGE_PIN R6 IOSTANDARD LVTTL} [get_ports USB_NXT]
#set_property -dict {PACKAGE_PIN Y9 IOSTANDARD LVTTL} [get_ports USB_OC]
#set_property -dict {PACKAGE_PIN T6 IOSTANDARD LVTTL} [get_ports USB_STP]


#
#	Gigabits
#
#set_property -dict {PACKAGE_PIN AB1 IOSTANDARD LVTTL} [get_ports DP_AUX_N]
#set_property -dict {PACKAGE_PIN Y2 IOSTANDARD LVTTL} [get_ports DP_AUX_N]
#set_property -dict {PACKAGE_PIN AA1 IOSTANDARD LVTTL} [get_ports DP_AUX_P]
#set_property -dict {PACKAGE_PIN W2 IOSTANDARD LVTTL} [get_ports DP_AUX_P]
#set_property -dict {PACKAGE_PIN V4 IOSTANDARD LVTTL} [get_ports DP_HPD]

#set_property -dict {PACKAGE_PIN A8 IOSTANDARD LVTTL} [get_ports LANE_0_RX_N]
#set_property -dict {PACKAGE_PIN B8 IOSTANDARD LVTTL} [get_ports LANE_0_RX_P]
#set_property -dict {PACKAGE_PIN A4 IOSTANDARD LVTTL} [get_ports LANE_0_TX_N]
#set_property -dict {PACKAGE_PIN B4 IOSTANDARD LVTTL} [get_ports LANE_0_TX_P]
#set_property -dict {PACKAGE_PIN C11 IOSTANDARD LVTTL} [get_ports LANE_1_RX_N]
#set_property -dict {PACKAGE_PIN D11 IOSTANDARD LVTTL} [get_ports LANE_1_RX_P]
#set_property -dict {PACKAGE_PIN C5 IOSTANDARD LVTTL} [get_ports LANE_1_TX_N]
#set_property -dict {PACKAGE_PIN D5 IOSTANDARD LVTTL} [get_ports LANE_1_TX_P]
#set_property -dict {PACKAGE_PIN A10 IOSTANDARD LVTTL} [get_ports LANE_2_RX_N]
#set_property -dict {PACKAGE_PIN B10 IOSTANDARD LVTTL} [get_ports LANE_2_RX_P]
#set_property -dict {PACKAGE_PIN A6 IOSTANDARD LVTTL} [get_ports LANE_2_TX_N]
#set_property -dict {PACKAGE_PIN B6 IOSTANDARD LVTTL} [get_ports LANE_2_TX_P]
#set_property -dict {PACKAGE_PIN C9 IOSTANDARD LVTTL} [get_ports LANE_3_RX_N]
#set_property -dict {PACKAGE_PIN D9 IOSTANDARD LVTTL} [get_ports LANE_3_RX_P]
#set_property -dict {PACKAGE_PIN C7 IOSTANDARD LVTTL} [get_ports LANE_3_TX_N]
#set_property -dict {PACKAGE_PIN D7 IOSTANDARD LVTTL} [get_ports LANE_3_TX_P]
#set_property -dict {PACKAGE_PIN E6 IOSTANDARD LVTTL} [get_ports MGT_CLK_0_N]
#set_property -dict {PACKAGE_PIN F6 IOSTANDARD LVTTL} [get_ports MGT_CLK_0_P]
#set_property -dict {PACKAGE_PIN E10 IOSTANDARD LVTTL} [get_ports MGT_CLK_1_N]
#set_property -dict {PACKAGE_PIN F10 IOSTANDARD LVTTL} [get_ports MGT_CLK_1_P]
#set_property -dict {PACKAGE_PIN F8 IOSTANDARD LVTTL} [get_ports N$118]
#set_property -dict {PACKAGE_PIN V3 IOSTANDARD LVTTL} [get_ports PCIE_PERST_N]
#set_property -dict {PACKAGE_PIN V5 IOSTANDARD LVTTL} [get_ports PCIE_WAKE_N]


#
#	CONFIG
#

#set_property -dict {PACKAGE_PIN G11 IOSTANDARD LVTTL} [get_ports FC_DONE]
#set_property -dict {PACKAGE_PIN U12 IOSTANDARD LVTTL} [get_ports FC_INIT_NCONFIG]
#set_property -dict {PACKAGE_PIN N12 IOSTANDARD LVTTL} [get_ports FC_PROG_NSTATUS]
#set_property -dict {PACKAGE_PIN L12 IOSTANDARD LVTTL} [get_ports FPGA_CCLK_INTERNAL]
#set_property -dict {PACKAGE_PIN T19 IOSTANDARD LVTTL} [get_ports FPGA_CSO]
#set_property -dict {PACKAGE_PIN P21 IOSTANDARD LVTTL} [get_ports FPGA_D02]
#set_property -dict {PACKAGE_PIN R21 IOSTANDARD LVTTL} [get_ports FPGA_D03]
#set_property -dict {PACKAGE_PIN U10 IOSTANDARD LVTTL} [get_ports FPGA_M1]
#set_property -dict {PACKAGE_PIN U9 IOSTANDARD LVTTL} [get_ports FPGA_M2]
#set_property -dict {PACKAGE_PIN R22 IOSTANDARD LVTTL} [get_ports FPGA_MISO_INTERNAL]
#set_property -dict {PACKAGE_PIN P22 IOSTANDARD LVTTL} [get_ports FPGA_MOSI]
#set_property -dict {PACKAGE_PIN V12 IOSTANDARD LVTTL} [get_ports FPGA_TCK]
#set_property -dict {PACKAGE_PIN R13 IOSTANDARD LVTTL} [get_ports FPGA_TDI]
#set_property -dict {PACKAGE_PIN U13 IOSTANDARD LVTTL} [get_ports FPGA_TDO]
#set_property -dict {PACKAGE_PIN T13 IOSTANDARD LVTTL} [get_ports FPGA_TMS]

#
#	Weird stuff
#

#set_property -dict {PACKAGE_PIN N3 IOSTANDARD LVTTL} [get_ports VREF_DDR]
#set_property -dict {PACKAGE_PIN E3 IOSTANDARD LVTTL} [get_ports VREF_DDR]
