
PROG = dhry

CSTD = KnR
WARNS = 1

DHRY_CFLAGS += -Ofast
DHRY_CFLAGS += -finline-limit=128

CFILES = dhry_cheat.c miscfn.c \
	../lib/div.c ../lib/printf.c ../lib/sio.c

ASFILES = ../lib/start.S

include ../conf/f32c.mk

../lib/div.o:	Makefile ../lib/div.c
	${CC} -DOPTIMIZED_DIVSI3 -c -o ../lib/div.o ../lib/div.c

# Specialized build options for dhry_*.c files

dhry_cheat.o:	Makefile dhry.h ../include/string.h dhry_cheat.c
	${CC} ${DHRY_CFLAGS} -c -o dhry_cheat.o dhry_cheat.c
