--- Makefile.org	2015-05-27 15:35:41.809814400 +0200
+++ Makefile	2015-05-27 15:35:41.934614700 +0200
@@ -26,21 +26,8 @@
 	@echo "Check run1.log and run2.log for results."
 	@echo "See readme.txt for run and reporting rules." 
 	
-ifndef PORT_DIR
-# Ports for a couple of common self hosted platforms
-UNAME=$(shell if [[ `uname 2> /dev/null` ]] ; then uname ; fi)
-ifneq (,$(findstring CYGWIN,$(UNAME)))
-PORT_DIR=cygwin
-endif
-ifneq (,$(findstring Linux,$(UNAME)))
-MACHINE=$(shell uname -m)
-ifneq (,$(findstring 64,$(MACHINE)))
-PORT_DIR=linux64
-else
-PORT_DIR=linux
-endif
-endif
-endif
+PORT_DIR=f32c
+
 ifndef PORT_DIR
 $(error PLEASE define PORT_DIR! (e.g. make PORT_DIR=simple)) 
 endif
@@ -58,7 +45,8 @@
 
 CFLAGS += -DITERATIONS=$(ITERATIONS)
 
-CORE_FILES = core_list_join core_main core_matrix core_state core_util
+CORE_FILES = core_list_join core_main core_matrix core_state core_util \
+		../../lib/src/sio_poll
 ORIG_SRCS = $(addsuffix .c,$(CORE_FILES))
 SRCS = $(ORIG_SRCS) $(PORT_SRCS)
 OBJS = $(addprefix $(OPATH),$(addsuffix $(OEXT),$(CORE_FILES)) $(PORT_OBJS))
@@ -81,6 +69,8 @@
 compile: $(OPATH) $(OPATH)$(PORT_DIR) $(OBJS) $(HEADERS) 
 link: compile 
 	$(LD) $(LFLAGS) $(XLFLAGS) $(OBJS) $(LOUTCMD)
+	$(ARCH)-elf-objcopy -O binary coremark.$(ARCH) coremark.bin
+	$(ARCH)-elf-objcopy -O srec coremark.$(ARCH) coremark.hex
 	
 else
 
@@ -88,6 +78,8 @@
 	$(CC) $(CFLAGS) $(XCFLAGS) $(SRCS) $(OUTCMD)
 link: compile 
 	@echo "Link performed along with compile"
+	$(ARCH)-elf-objcopy -O binary coremark.$(ARCH) coremark.bin
+	$(ARCH)-elf-objcopy -O srec coremark.$(ARCH) coremark.hex
 
 endif
 
@@ -126,6 +118,7 @@
 .PHONY: clean
 clean:
 	rm -f $(OUTFILE) $(OPATH)*.log *.info $(OPATH)index.html $(PORT_CLEAN)
+	rm -f coremark.hex coremark.bin
 
 .PHONY: force_rebuild
 force_rebuild:
